import type { RawPack } from './packTypes';

// More official packs (see packTypes.ts for the format). Same content rules as cards.ts.
export const MORE_PACKS: RawPack[] = [
  ['lives', 'Two Full Lives', '🧩', 'Routines, rituals and "how I like things"', [
    { t: 'choice', q: 'Towel on the bed: crime or fine?', o: [['crime', '🚨', 'A crime'], ['fine', '😌', 'Totally fine'], ['depends', '🤷', 'Depends whose bed']] },
    { t: 'choice', q: 'Thermostat wars: which team are you?', o: [['warm', '🔥', 'Toasty warm'], ['cool', '❄️', 'Crisp and cool'], ['blanket', '🛌', 'Cool room, big blanket']] },
    { t: 'choice', q: 'You and your alarm?', o: [['first', '⏰', 'Up on the first ring'], ['snooze', '😴', 'Snooze, snooze, snooze'], ['five', '🔔', 'Five alarms, one purpose'], ['none', '🌞', 'No alarm, body clock']] },
    { t: 'multi', q: 'Your Sunday ritual?', o: [['liein', '🛌', 'A long lie-in'], ['brunch', '🥐', 'Slow brunch'], ['walk', '🚶', 'A long walk'], ['clean', '🧹', 'Big clean, music on'], ['call', '📞', 'A family video call'], ['prep', '🍱', 'Meal prep for the week'], ['plan', '🗓️', 'Plan the week ahead']] },
    { t: 'choice', q: 'Loading the dishwasher: system or chaos?', o: [['system', '📐', 'There is one correct way'], ['chaos', '🎲', 'If it fits, it ships'], ['hand', '🧽', 'I just wash by hand']] },
    { t: 'choice', q: 'Weekends: planner or spontaneous?', o: [['plan', '🗓️', 'Planned to the hour'], ['loose', '🧭', 'Rough plan, open mind'], ['spont', '🎈', 'Decide on the day']] },
    { t: 'line', q: 'A habit of mine that is not up for debate 😅', ph: 'One line ✍️', banner: 'Two non-negotiables 😅' },
    { t: 'nhie', q: 'reorganised someone else\'s kitchen cupboard without asking 🫙' },
    { t: 'choice', q: 'Toothpaste tube: squeeze from the end or the middle?', o: [['end', '📏', 'From the end, neatly'], ['middle', '✊', 'Wherever I grab it'], ['roll', '🌀', 'Rolled up like a pro']] },
    { t: 'choice', q: 'Packing for a trip?', o: [['week', '🧳', 'Packed a week early'], ['night', '🌙', 'The night before'], ['panic', '⏱️', 'Morning of, in a panic']] },
    { t: 'multi', q: 'Things you are a little fussy about?', o: [['pillow', '🛏️', 'My pillow'], ['mug', '☕', 'My mug'], ['side', '↔️', 'My side of the bed'], ['chai', '🫖', 'How my chai is made'], ['remote', '📺', 'The remote'], ['shoes', '👟', 'Shoes off at the door'], ['towels', '🧺', 'Towels folded my way']] },
    { t: 'line', q: 'One rule you learned the hard way?', ph: 'One line ✍️', banner: 'Two lessons, one laugh 📜' },
    { t: 'choice', q: 'Clean laundry lives…', o: [['folded', '👕', 'Folded the same day'], ['chair', '🪑', 'On the famous chair'], ['basket', '🧺', 'In the basket till worn']] },
    { t: 'nhie', q: 'set an alarm to remind me about another alarm ⏰' },
    { t: 'choice', q: 'Screens in bed?', o: [['reel', '📱', 'Just one more reel'], ['book', '📚', 'Book or nothing'], ['podcast', '🎧', 'A podcast to drift off'], ['none', '🌙', 'Lights out, straight to sleep']] },
    { t: 'line', q: 'Your perfect ordinary weekday evening?', ph: 'One line ✍️', banner: 'Two quiet evenings 🌙' },
  ]],

  ['nokjhok', 'Nok-Jhok and Nazar', '😏', 'Teasing, flirting and a little filmy', [
    { t: 'choice', q: 'Who would steal the last bite?', o: [['me', '😏', 'Me, obviously'], ['you', '😇', 'You, and I would let you'], ['split', '🍴', 'We split it, fair and square']] },
    { t: 'line', q: 'Your most dramatic filmy moment?', ph: 'One line ✍️', banner: 'Two filmy moments 🎬' },
    { t: 'choice', q: 'Rate my texting flirting, 1 to 5', o: [['one', '🥶', '1: Ice cold'], ['two', '🙂', '2: Very polite'], ['three', '😊', '3: Getting there'], ['four', '😏', '4: Smooth'], ['five', '🔥', '5: Full filmy level']] },
    { t: 'line', q: 'A secret code word for "I miss you"?', ph: 'Just the word 🤫', banner: 'Two secret codes 🤫' },
    { t: 'choice', q: 'Slow dance in the kitchen or run in the rain?', o: [['kitchen', '💃', 'Slow dance in the kitchen'], ['rain', '🌧️', 'Run in the rain'], ['both', '🎶', 'Both, same evening']] },
    { t: 'choice', q: 'Forehead kisses or hand holding?', o: [['forehead', '😘', 'Forehead kisses'], ['hands', '🫶', 'Hand holding'], ['both', '💞', 'Why choose?']] },
    { t: 'line', q: 'The moment you knew you had a crush?', ph: 'One line ✍️', banner: 'Two little moments 💘' },
    { t: 'nhie', q: 'reread a message five times before sending it 📱' },
    { t: 'choice', q: 'Our eyes meet across a room. You…', o: [['wink', '😉', 'Wink'], ['smile', '😊', 'Smile and look away'], ['walk', '🚶', 'Walk straight over'], ['text', '📱', 'Text from across the room']] },
    { t: 'multi', q: 'Filmy moments you secretly want?', o: [['rain', '🌧️', 'Dancing in the rain'], ['slowmo', '🎞️', 'A slow-motion entry'], ['sing', '🎤', 'Someone singing to me'], ['dupatta', '🧣', 'Dupatta in the wind'], ['flowers', '💐', 'Surprise flowers'], ['balcony', '🌙', 'Midnight balcony chat'], ['station', '🚉', 'A dramatic station goodbye']] },
    { t: 'choice', q: 'Your teasing style?', o: [['roast', '🔥', 'Gentle roasting'], ['voice', '🎭', 'Doing your voice'], ['nick', '🏷️', 'Silly nicknames'], ['sweet', '🍯', 'Too sweet to tease']] },
    { t: 'choice', q: 'Our nok-jhok usually ends with…', o: [['sorry', '🙏', 'Someone says sorry first'], ['laugh', '😂', 'Whoever laughs first loses'], ['snack', '🍫', 'A peace-offering snack'], ['hug', '🤗', 'A hug, all forgotten']] },
    { t: 'nhie', q: 'practised a flirty line in the mirror 🪞' },
    { t: 'choice', q: 'Good-night message style?', o: [['long', '📜', 'A long sweet one'], ['emoji', '🌙', 'Just an emoji'], ['voice', '🎙️', 'A sleepy voice note'], ['call', '📞', 'Call till someone dozes off']] },
    { t: 'line', q: 'One thing I do that makes you blush?', ph: 'One line ✍️', banner: 'Two blushing faces ☺️' },
    { t: 'choice', q: 'Matching outfits someday?', o: [['full', '👯', 'Yes, fully coordinated'], ['subtle', '🎨', 'Subtly matching colours'], ['never', '🙅', 'Never, ever']] },
  ]],

  ['world', 'Teach Me Your World', '🌏', 'Words, food and ways from where you grew up', [
    { t: 'line', q: 'A word from your home language everyone should know?', ph: 'The word, and what it means ✍️', banner: 'Two new words 🗣️' },
    { t: 'line', q: 'Your family group chat in 3 emojis?', ph: 'Three emojis 😄', banner: 'Two group chats, six emojis 📱' },
    { t: 'choice', q: 'Shoes at the door?', o: [['off', '👟', 'Always off'], ['on', '👞', 'On is fine'], ['slippers', '🩴', 'House slippers ready']] },
    { t: 'line', q: 'Comfort food from where you grew up?', ph: 'One dish ✍️', banner: 'Two comfort plates 🍲' },
    { t: 'multi', q: 'What would you teach me first?', o: [['hello', '👋', 'How to say hello'], ['recipe', '🍽️', 'A family recipe'], ['dance', '💃', 'A dance step'], ['game', '🎲', 'A childhood game'], ['song', '🎵', 'A song title to look up'], ['manners', '🙏', 'Home manners'], ['slang', '😎', 'Local slang']] },
    { t: 'line', q: 'A festival you would take me to?', ph: 'One line ✍️', banner: 'Two festival invites 🎊' },
    { t: 'nhie', q: 'mispronounced a dish name with total confidence 🍛' },
    { t: 'choice', q: 'Learning my home language: how far would you go?', o: [['fluent', '🎓', 'Aim for fluent'], ['basics', '🗣️', 'Basics and the jokes'], ['food', '🍛', 'Just the food words'], ['songs', '🎶', 'Whatever songs teach me']] },
    { t: 'line', q: 'A saying your family uses?', ph: 'The saying, and what it means ✍️', banner: 'Two family sayings 💬' },
    { t: 'choice', q: 'Eating with your hands?', o: [['pro', '✋', 'Pro, obviously'], ['learning', '🤲', 'Still learning'], ['cutlery', '🍴', 'Cutlery, please'], ['depends', '🍚', 'Depends on the dish']] },
    { t: 'choice', q: 'Visiting someone\'s home for the first time?', o: [['early', '⏰', 'Early, to help out'], ['ontime', '🕰️', 'Exactly on time'], ['late', '😅', 'A little late, as is tradition']] },
    { t: 'line', q: 'Explain one tradition in one line?', ph: 'One line ✍️', banner: 'Two traditions, explained 🌏' },
    { t: 'multi', q: 'From home, you would want in our kitchen…', o: [['spice', '🌶️', 'A spice box'], ['achaar', '🫙', 'Homemade achaar'], ['tea', '🫖', 'A favourite tea'], ['bread', '🍞', 'Home-style bread'], ['snack', '🍘', 'A snack from home'], ['sweet', '🍬', 'A family sweet']] },
    { t: 'choice', q: 'At a big family gathering you would be…', o: [['dance', '💃', 'On the dance floor'], ['food', '🍲', 'Near the food'], ['chat', '💬', 'Chatting with everyone'], ['watch', '👀', 'Quietly taking it all in']] },
    { t: 'line', q: 'A childhood game from where you grew up?', ph: 'Just the name ✍️', banner: 'Two childhoods 🪁' },
    { t: 'choice', q: 'Mixing our traditions someday?', o: [['all', '🌏', 'Celebrate everything'], ['new', '✨', 'Make new ones'], ['pick', '🎁', 'Pick our favourites']] },
  ]],

  ['festive', 'Festivals of Everyone', '🪔', 'Eid to Onam, Bihu to Christmas, and one of our own', [
    { t: 'choice', q: 'Invited to an iftar: first thing you reach for?', o: [['dates', '🌴', 'Dates'], ['fruit', '🍉', 'Fruit chaat'], ['sherbet', '🥤', 'Rooh Afza sherbet'], ['pakora', '🧅', 'Pakoras', 'og'], ['haleem', '🍲', 'Haleem', 'nonveg'], ['sweet', '🍮', 'Something sweet']] },
    { t: 'nhie', q: 'wished someone “Navroz Mubarak” on the Parsi New Year 🌸' },
    { t: 'choice', q: 'Chaand raat, the night before Eid: where would you be?', o: [['mehendi', '🌿', 'Getting mehendi done'], ['market', '🛍️', 'At the late-night market'], ['bangles', '💫', 'Bangle shopping'], ['outfit', '👗', 'Picking the Eid outfit'], ['moon', '🌙', 'Watching for the moon']] },
    { t: 'choice', q: 'Onam sadya on a banana leaf: what do you save for last?', o: [['payasam', '🍮', 'Payasam'], ['chips', '🍌', 'Banana chips'], ['avial', '🥕', 'Avial', 'og'], ['sambar', '🍛', 'Sambar and rice'], ['pappadam', '🫓', 'Pappadam']] },
    { t: 'choice', q: 'Making a pookalam, the Onam flower carpet: your role?', o: [['design', '🎨', 'Design lead'], ['petals', '🌼', 'Petal sorter'], ['photo', '📸', 'Chief photographer'], ['snack', '🍌', 'Snack supervisor']] },
    { t: 'choice', q: 'Sankranti kite day: where are you?', o: [['fly', '🪁', 'Flying the kite'], ['spool', '🧵', 'Holding the spool'], ['cheer', '📣', 'Cheering from the roof'], ['chikki', '🥜', 'On chikki duty']] },
    { t: 'choice', q: 'Pongal morning: sweet or savoury?', o: [['sweet', '🍯', 'Sakkarai (sweet) pongal'], ['ven', '🍚', 'Ven (savoury) pongal'], ['both', '🤝', 'One of each'], ['cane', '🎋', 'Just the sugarcane']] },
    { t: 'multi', q: 'At a Bihu celebration, what would you try?', o: [['dance', '💃', 'A Bihu dance step'], ['pitha', '🍘', 'Til pitha'], ['laru', '🥥', 'Coconut laru'], ['dhol', '🥁', 'The dhol, live'], ['gamosa', '🧣', 'Wearing a gamosa']] },
    { t: 'choice', q: 'Navroz, the Parsi New Year: which sweet first?', o: [['ravo', '🍮', 'Ravo'], ['falooda', '🍧', 'Falooda'], ['sev', '🍜', 'Sweet sev'], ['custard', '🥧', 'Lagan nu custard', 'egg']] },
    { t: 'choice', q: 'Langar at a gurdwara on Gurpurab or Baisakhi: you would…', o: [['serve', '🥣', 'Serve with the volunteers'], ['roti', '🫓', 'Help make rotis'], ['wash', '🧽', 'Wash up after'], ['sit', '🙏', 'Sit and eat with everyone']] },
    { t: 'multi', q: 'Christmas, Kerala and Goa style: what do you want?', o: [['star', '⭐', 'A paper star on the balcony'], ['carols', '🎶', 'Midnight carols'], ['kuswar', '🍪', 'A plate of Goan kuswar'], ['lights', '✨', 'Fairy lights everywhere'], ['appam', '🥞', 'Appam and veg stew', 'og'], ['market', '🎄', 'A Christmas market']] },
    { t: 'choice', q: 'Durga Puja pandal hopping: your plan?', o: [['all', '🗺️', 'Every pandal in town'], ['one', '🏛️', 'One, done properly'], ['bhog', '🍛', 'Wherever the bhog is'], ['dhunuchi', '💃', 'Watching the dhunuchi dance']] },
    { t: 'choice', q: 'Diwali evening: diyas, rangoli or mithai?', o: [['diya', '🪔', 'Lighting diyas'], ['rangoli', '🎨', 'Making rangoli'], ['mithai', '🍬', 'Opening the mithai box'], ['calls', '📞', 'Calls with everyone']] },
    { t: 'choice', q: 'Paryushan (Jain) ends with everyone asking forgiveness. Easier for you?', o: [['first', '💬', 'Saying sorry first'], ['letgo', '🍃', 'Letting small things go'], ['both', '🙏', 'Both, still practising']] },
    { t: 'nhie', q: 'visited a vihara or monastery on Vesak, the Buddha Purnima full moon 🌕' },
    { t: 'choice', q: 'Buddha Purnima full moon: how would you spend the evening?', o: [['walk', '🌕', 'A full-moon walk'], ['quiet', '🕯️', 'A lamp and some quiet'], ['kheer', '🍚', 'Kheer under the moon'], ['vihara', '☸️', 'Visit a vihara']] },
    { t: 'nhie', q: 'joined a festival I had never celebrated and loved it 🎉' },
    { t: 'line', q: 'Our own celebration: which day would you make our festival?', ph: 'The day, and one way to mark it ✍️', banner: 'Two new festivals 🎊' },
  ]],

  ['dates', 'Date Plans', '🗓️', 'Date nights, dine-outs and weekends, big or free', [
    { t: 'choice', q: 'Date night this week: which size?', o: [['free', '🌅', 'Free: a sunset walk'], ['small', '☕', 'Small: chai and a chat'], ['big', '🍽️', 'Big: dress up, dine out']] },
    { t: 'multi', q: 'Dine-out cuisines you would pick?', o: [['south', '🥥', 'South Indian'], ['thali', '🍛', 'Gujarati thali'], ['italian', '🍕', 'Italian'], ['mexican', '🌮', 'Mexican'], ['thai', '🍜', 'Thai'], ['japanese', '🍱', 'Japanese'], ['chaat', '🫧', 'A chaat house']] },
    { t: 'choice', q: 'The dish you order every time?', o: [['paneer', '🧀', 'Paneer butter masala', 'og'], ['dosa', '🥞', 'Plain dosa'], ['thali', '🍛', 'A big thali'], ['pizza', '🍕', 'Margherita pizza'], ['pasta', '🍝', 'Pasta arrabbiata', 'og'], ['dal', '🍲', 'Dal, rice and papad'], ['biryani', '🍗', 'Chicken biryani', 'nonveg'], ['fishcurry', '🐟', 'Goan fish curry', 'nonveg']] },
    { t: 'choice', q: 'Street food crawl: first stop?', o: [['panipuri', '🫧', 'Pani puri', 'og'], ['vadapav', '🍔', 'Vada pav', 'og'], ['dhokla', '🟨', 'Dhokla'], ['jalebi', '🍥', 'Jalebi'], ['corn', '🌽', 'Masala corn'], ['kulfi', '🍦', 'Kulfi'], ['kebab', '🍢', 'Seekh kebab roll', 'nonveg']] },
    { t: 'choice', q: 'Breakfast date order?', o: [['masaladosa', '🥞', 'Masala dosa', 'og'], ['paratha', '🫓', 'Aloo paratha', 'og'], ['omelette', '🍳', 'Masala omelette', 'egg'], ['idli', '🍘', 'Idli and chutney'], ['khakhra', '🫖', 'Khakhra and chai'], ['bowl', '🍓', 'Fruit and yoghurt bowl'], ['toast', '🍞', 'Chilli cheese toast']] },
    { t: 'choice', q: 'Your dream Sunday together?', o: [['brunch', '🛋️', 'Lazy brunch at home'], ['market', '🥬', 'A farmers\' market wander'], ['trip', '🚗', 'A day trip somewhere new'], ['picnic', '🧺', 'Picnic in the park'], ['films', '🎬', 'A film marathon']] },
    { t: 'multi', q: 'Picnic basket must-haves?', o: [['sandwich', '🥪', 'Chutney sandwiches'], ['thepla', '🫓', 'Thepla'], ['fruit', '🍇', 'Cut fruit'], ['crisps', '🥔', 'Crisps', 'og'], ['chai', '🫖', 'A flask of chai'], ['nimbu', '🍋', 'Nimbu pani'], ['mithai', '🍬', 'A box of mithai']] },
    { t: 'choice', q: 'Long-distance date night?', o: [['cook', '🧑‍🍳', 'Cook-along on a call'], ['watch', '🎬', 'Watch party, same film'], ['walk', '🚶', 'Walk and talk on a call'], ['game', '🎲', 'Online game night'], ['letter', '✉️', 'Letters by post']] },
    { t: 'choice', q: 'Dessert date?', o: [['kulfi', '🍦', 'Kulfi'], ['gelato', '🍨', 'Gelato'], ['rabdi', '🍥', 'Jalebi with rabdi'], ['falooda', '🍧', 'Falooda'], ['cocoa', '🍫', 'Hot chocolate']] },
    { t: 'choice', q: 'Who picks the restaurant?', o: [['me', '🙋', 'Me, I have a list'], ['you', '🫵', 'You, I trust you'], ['spin', '🎡', 'Spin a wheel'], ['usual', '🔁', 'The usual place, always']] },
    { t: 'nhie', q: 'spent longer choosing a restaurant than eating there ⏳' },
    { t: 'choice', q: 'Sunset walk, sunrise walk, or starry night?', o: [['sunset', '🌅', 'Sunset walk'], ['sunrise', '🌄', 'Sunrise walk'], ['stars', '🌙', 'Starry night walk']] },
    { t: 'line', q: 'A free date idea you have always wanted to try?', ph: 'One line ✍️', banner: 'Two free dates 🆓' },
    { t: 'choice', q: 'Weekend plan?', o: [['museum', '🏛️', 'A free museum'], ['hike', '🥾', 'A little hike'], ['pottery', '🎨', 'A pottery class'], ['cook', '🏠', 'Cook together at home'], ['comedy', '🎤', 'A comedy night'], ['swim', '🏊', 'A swim, then chai']] },
    { t: 'choice', q: 'With dinner you would order…', o: [['chai', '☕', 'Masala chai'], ['mocktail', '🥤', 'A fancy mocktail'], ['lassi', '🥭', 'Mango lassi'], ['lime', '🍋', 'Fresh lime soda'], ['water', '💧', 'Just water, thanks']] },
    { t: 'line', q: 'Our first big date: where would you want it?', ph: 'One line ✍️', banner: 'Two big date dreams ✨' },
  ]],

  ['shop', 'Shopping Spree', '🛍️', 'Carts, colours, bargains and gift hints', [
    { t: 'choice', q: 'Your shopping style?', o: [['list', '📝', 'Strictly the list'], ['wander', '🚶', 'Wander and discover'], ['both', '🔁', 'List first, then wander']] },
    { t: 'choice', q: 'Your online cart right now?', o: [['done', '✅', 'Checked out in minutes'], ['weeks', '🛒', 'Sitting there for weeks'], ['wish', '💭', 'It is a wishlist now'], ['sale', '⏳', 'Waiting for a sale']] },
    { t: 'line', q: 'A colour you love but never wear?', ph: 'Just the colour 🎨', banner: 'Two brave colours 🌈' },
    { t: 'choice', q: 'Sale season strategy?', o: [['first', '🏃', 'First in at midnight'], ['plan', '📋', 'List and budget ready'], ['skip', '🙅', 'Avoid the madness'], ['last', '🧺', 'Last-day bargains']] },
    { t: 'line', q: 'A gift I would secretly love?', ph: 'One line ✍️', banner: 'Two gift hints 🎁' },
    { t: 'line', q: 'Please never buy me…', ph: 'Finish the line ✍️', banner: 'Two gift warnings 🙅' },
    { t: 'choice', q: 'Trying things on for me?', o: [['show', '💃', 'Full fashion show'], ['few', '👍', 'One or two, sure'], ['photos', '📸', 'Photos from the changing room'], ['no', '🙈', 'Not a chance']] },
    { t: 'choice', q: 'Bargaining at a market?', o: [['pro', '🤝', 'Bargaining pro'], ['walk', '🚶', 'Pretend to walk away'], ['pay', '💸', 'Pay the price, too shy'], ['you', '🫵', 'You do the talking']] },
    { t: 'line', q: 'One thing you always overspend on?', ph: 'One line ✍️', banner: 'Two little splurges 💸' },
    { t: 'multi', q: 'Where do you love to shop?', o: [['mall', '🏬', 'The mall'], ['online', '📱', 'Online'], ['market', '🧺', 'Street markets'], ['thrift', '♻️', 'Charity and thrift shops'], ['local', '🏪', 'Small local shops'], ['books', '📚', 'Bookshops']] },
    { t: 'choice', q: 'Thrift challenge: small budget, we dress each other?', o: [['in', '🙌', "I'm in"], ['maybe', '🤔', 'Maybe, tell me more'], ['watch', '👀', 'I will just watch']] },
    { t: 'choice', q: 'Window shopping is…', o: [['fun', '🪟', 'The best free fun'], ['torture', '😩', 'Pure torture'], ['danger', '💳', 'Dangerous for my card']] },
    { t: 'nhie', q: 'bought the same thing twice because I forgot I had it 🛍️' },
    { t: 'choice', q: 'Returns?', o: [['always', '📦', 'Return it, no guilt'], ['never', '🫣', 'Never get round to it'], ['keep', '🤷', 'Keep it, it might fit someday']] },
    { t: 'multi', q: 'You could browse all day for…', o: [['shoes', '👟', 'Shoes'], ['books', '📚', 'Books'], ['kitchen', '🥘', 'Kitchen gadgets'], ['stationery', '✏️', 'Stationery'], ['plants', '🪴', 'Plants'], ['clothes', '👗', 'Clothes'], ['tech', '🎧', 'Tech gadgets']] },
    { t: 'nhie', q: 'added something to the cart just to get free delivery 🚚' },
  ]],
];
