// Movie Night catalogue: films, series and comedy specials from anywhere, 1950s to now.
// Rules (CLAUDE.md): emoji plus title and year only, never posters or artwork. Hooks are our own
// one-line words: no quotes, dialogue, lyrics or plot-twist spoilers, no alcohol, meat or pets,
// nothing sexual. Not tied to any service, so no streaming service is ever named here.

export type TitleKind = 'movie' | 'series' | 'special';
export type TitleLang =
  | 'Hindi' | 'English' | 'Gujarati' | 'Punjabi' | 'Tamil' | 'Telugu' | 'Malayalam' | 'Bengali'
  | 'Marathi' | 'Kannada' | 'Korean' | 'Japanese' | 'Spanish' | 'Other';
export type Genre =
  | 'romance' | 'comedy' | 'drama' | 'family' | 'thriller' | 'horror' | 'scifi' | 'fantasy' | 'spy'
  | 'action' | 'crime' | 'mystery' | 'animation' | 'documentary' | 'sports' | 'music' | 'standup'
  | 'reality' | 'anime' | 'historical';

export interface CatalogTitle {
  id: string;
  kind: TitleKind;
  e: string;
  t: string;
  year: number;
  lang: TitleLang;
  genres: Genre[];
  hook: string;
}

const M: TitleKind = 'movie';
const S: TitleKind = 'series';
const X: TitleKind = 'special';

const T = (id: string, kind: TitleKind, e: string, t: string, year: number, lang: TitleLang, genres: Genre[], hook: string): CatalogTitle => ({
  id, kind, e, t, year, lang, genres, hook,
});

const EN: TitleLang = 'English';
const HI: TitleLang = 'Hindi';
const GU: TitleLang = 'Gujarati';
const PA: TitleLang = 'Punjabi';
const TA: TitleLang = 'Tamil';
const TE: TitleLang = 'Telugu';
const ML: TitleLang = 'Malayalam';
const BN: TitleLang = 'Bengali';
const MR: TitleLang = 'Marathi';
const KN: TitleLang = 'Kannada';
const KO: TitleLang = 'Korean';
const JA: TitleLang = 'Japanese';
const ES: TitleLang = 'Spanish';
const OT: TitleLang = 'Other';

export const CATALOG: CatalogTitle[] = [
  // ---------------------------------------------------------------- English series: comedy
  T('friends', S, '☕', 'Friends', 1994, EN, ['comedy', 'romance'], 'Six friends, one coffee shop and a very orange sofa.'),
  T('seinfeld', S, '🥨', 'Seinfeld', 1989, EN, ['comedy'], 'Four friends turn tiny annoyances into big theories.'),
  T('frasier', S, '📻', 'Frasier', 1993, EN, ['comedy', 'family'], 'A fussy radio psychiatrist shares a flat with his dad.'),
  T('fresh-prince', S, '👑', 'The Fresh Prince of Bel-Air', 1990, EN, ['comedy', 'family'], 'A West Philly teen moves in with his posh relatives.'),
  T('the-office-uk', S, '🖨️', 'The Office (UK)', 2001, EN, ['comedy'], 'A paper company in Slough and a boss who tries far too hard.'),
  T('the-office-us', S, '📎', 'The Office', 2005, EN, ['comedy', 'romance'], 'Cringe, pranks and a slow-burn romance at a paper company.'),
  T('himym', S, '🟨', 'How I Met Your Mother', 2005, EN, ['comedy', 'romance'], 'A dad tells his kids a very, very long love story.'),
  T('big-bang-theory', S, '🔬', 'The Big Bang Theory', 2007, EN, ['comedy'], 'Brilliant scientists, zero social skills, one new neighbour.'),
  T('brooklyn-99', S, '🚔', 'Brooklyn Nine-Nine', 2013, EN, ['comedy', 'crime'], 'A goofy detective squad with a deadpan captain.'),
  T('parks-and-rec', S, '🌳', 'Parks and Recreation', 2009, EN, ['comedy'], 'A tireless optimist tries to build one small-town park.'),
  T('modern-family', S, '🏡', 'Modern Family', 2009, EN, ['comedy', 'family'], 'Three branches of one big, loud, loving family.'),
  T('schitts-creek', S, '🏚️', "Schitt's Creek", 2015, EN, ['comedy', 'family'], 'A rich family goes broke and moves to a tiny town.'),
  T('the-good-place', S, '☁️', 'The Good Place', 2016, EN, ['comedy', 'fantasy'], 'An afterlife mix-up leads to lessons in being good.'),
  T('ted-lasso', S, '⚽', 'Ted Lasso', 2020, EN, ['comedy', 'sports', 'drama'], 'An American coach, an English football club, pure kindness.'),
  T('omitb', S, '🏢', 'Only Murders in the Building', 2021, EN, ['comedy', 'mystery'], 'Three neighbours start a true-crime podcast about their block.'),
  T('abbott-elementary', S, '🍎', 'Abbott Elementary', 2021, EN, ['comedy'], 'Underfunded, overworked, big-hearted school teachers.'),
  T('ghosts-uk', S, '👻', 'Ghosts', 2019, EN, ['comedy', 'fantasy'], 'A couple inherits a country house full of bickering ghosts.'),
  T('derry-girls', S, '🏫', 'Derry Girls', 2018, EN, ['comedy', 'family'], 'Teen chaos at a convent school in 1990s Northern Ireland.'),
  T('the-it-crowd', S, '💻', 'The IT Crowd', 2006, EN, ['comedy'], 'Two tech nerds and their clueless new boss in the basement.'),
  T('mr-bean', S, '🧸', 'Mr. Bean', 1990, EN, ['comedy', 'family'], 'A man, his teddy and almost no words at all.'),
  T('goodness-gracious-me', S, '🪔', 'Goodness Gracious Me', 1998, EN, ['comedy'], 'Classic British Asian sketches that flip the script.'),
  T('community', S, '📚', 'Community', 2009, EN, ['comedy'], 'A misfit study group at a very odd community college.'),
  T('new-girl', S, '🏠', 'New Girl', 2011, EN, ['comedy', 'romance'], 'A quirky teacher moves in with three single guys.'),
  T('superstore', S, '🛒', 'Superstore', 2015, EN, ['comedy'], 'Life on the shop floor of a giant big-box store.'),
  T('kims-convenience', S, '🏪', "Kim's Convenience", 2016, EN, ['comedy', 'family'], 'A Korean-Canadian family runs a corner shop in Toronto.'),
  T('never-have-i-ever', S, '📓', 'Never Have I Ever', 2020, EN, ['comedy', 'family', 'romance'], 'An Indian-American teen juggles grief, school and crushes.'),
  T('gilmore-girls', S, '📖', 'Gilmore Girls', 2000, EN, ['family', 'comedy', 'drama'], 'A fast-talking mum and daughter in a cosy small town.'),
  T('marvelous-mrs-maisel', S, '🎤', 'The Marvelous Mrs. Maisel', 2017, EN, ['comedy', 'drama'], 'A 1950s housewife discovers she is brilliant at stand-up.'),
  T('yes-minister', S, '🏛️', 'Yes Minister', 1980, EN, ['comedy'], 'A minister versus the civil servants who really run things.'),
  T('fawlty-towers', S, '🛎️', 'Fawlty Towers', 1975, EN, ['comedy'], 'The rudest hotel owner on the English seaside.'),
  T('blackadder', S, '🪶', 'Blackadder', 1983, EN, ['comedy', 'historical'], 'One sly schemer, reborn across centuries of history.'),
  T('gavin-and-stacey', S, '💑', 'Gavin & Stacey', 2007, EN, ['comedy', 'romance', 'family'], 'An Essex boy, a Welsh girl and two very different families.'),
  T('friday-night-dinner', S, '🍽️', 'Friday Night Dinner', 2011, EN, ['comedy', 'family'], 'Two brothers come home every week for a chaotic family meal.'),
  T('ms-marvel', S, '⚡', 'Ms. Marvel', 2022, EN, ['fantasy', 'action', 'family'], 'A Pakistani-American teen fangirl gets real superpowers.'),
  T('the-simpsons', S, '🍩', 'The Simpsons', 1989, EN, ['animation', 'comedy', 'family'], 'The yellow family that has been on TV for decades.'),

  // ---------------------------------------------------------------- English series: drama, crime, mystery
  T('the-bear', S, '🔪', 'The Bear', 2022, EN, ['drama', 'comedy'], 'A top chef comes home to rescue a chaotic family sandwich shop.'),
  T('succession', S, '💼', 'Succession', 2018, EN, ['drama'], 'Siblings scheme to take over their father’s media empire.'),
  T('the-crown', S, '👑', 'The Crown', 2016, EN, ['historical', 'drama'], 'The reign of Queen Elizabeth II, decade by decade.'),
  T('downton-abbey', S, '🏰', 'Downton Abbey', 2010, EN, ['historical', 'drama', 'family'], 'An aristocratic family and their staff in a changing England.'),
  T('bridgerton', S, '💐', 'Bridgerton', 2020, EN, ['romance', 'historical'], 'Regency-era ballrooms, gossip sheets and matchmaking.'),
  T('emily-in-paris', S, '🗼', 'Emily in Paris', 2020, EN, ['romance', 'comedy'], 'A Chicago marketer lands a job in Paris, outfits and all.'),
  T('heartstopper', S, '🍂', 'Heartstopper', 2022, EN, ['romance', 'drama'], 'Two schoolboys become friends, then something sweeter.'),
  T('summer-i-turned-pretty', S, '🏖️', 'The Summer I Turned Pretty', 2022, EN, ['romance', 'drama'], 'Beach-house summers and one very complicated crush.'),
  T('the-queens-gambit', S, '♟️', "The Queen's Gambit", 2020, EN, ['drama', 'sports'], 'An orphan girl becomes a chess prodigy in the 1960s.'),
  T('chernobyl', S, '☢️', 'Chernobyl', 2019, EN, ['historical', 'drama'], 'The 1986 nuclear disaster and the people who faced it.'),
  T('band-of-brothers', S, '🪖', 'Band of Brothers', 2001, EN, ['historical', 'action', 'drama'], 'One company of soldiers from training to the end of WWII.'),
  T('the-west-wing', S, '🇺🇸', 'The West Wing', 1999, EN, ['drama'], 'Fast walks and faster talks inside the White House.'),
  T('er', S, '🚑', 'ER', 1994, EN, ['drama'], 'Doctors and nurses in a busy Chicago emergency room.'),
  T('greys-anatomy', S, '🩺', "Grey's Anatomy", 2005, EN, ['drama', 'romance'], 'Surgical interns, long shifts and tangled hearts.'),
  T('house', S, '💊', 'House', 2004, EN, ['drama', 'mystery'], 'A grumpy genius doctor solves medical puzzles.'),
  T('suits', S, '👔', 'Suits', 2011, EN, ['drama'], 'A brilliant dropout bluffs his way into a top law firm.'),
  T('the-morning-show', S, '🌅', 'The Morning Show', 2019, EN, ['drama'], 'Power struggles behind a big breakfast-TV show.'),
  T('breaking-bad', S, '⚗️', 'Breaking Bad', 2008, EN, ['crime', 'drama', 'thriller'], 'A chemistry teacher makes a very bad career change.'),
  T('better-call-saul', S, '⚖️', 'Better Call Saul', 2015, EN, ['crime', 'drama'], 'A small-time lawyer slowly bends every rule.'),
  T('sherlock', S, '🔎', 'Sherlock', 2010, EN, ['crime', 'mystery'], 'The great detective solves cases in modern London.'),
  T('poirot', S, '🥸', "Agatha Christie's Poirot", 1989, EN, ['mystery', 'crime', 'historical'], 'A tidy Belgian detective and his little grey cells.'),
  T('midsomer-murders', S, '🌾', 'Midsomer Murders', 1997, EN, ['mystery', 'crime'], 'Pretty English villages with a surprising crime rate.'),
  T('death-in-paradise', S, '🏝️', 'Death in Paradise', 2011, EN, ['mystery', 'comedy'], 'British detectives solve puzzles on a sunny Caribbean island.'),
  T('broadchurch', S, '🌊', 'Broadchurch', 2013, EN, ['crime', 'mystery', 'drama'], 'A seaside town is shaken by a mystery on the beach.'),
  T('line-of-duty', S, '🚨', 'Line of Duty', 2012, EN, ['crime', 'thriller'], 'An anti-corruption unit investigates its own police.'),
  T('bodyguard', S, '🛡️', 'Bodyguard', 2018, EN, ['thriller', 'drama'], 'A war veteran is assigned to protect a controversial minister.'),
  T('mindhunter', S, '🧠', 'Mindhunter', 2017, EN, ['crime', 'thriller'], 'Early FBI agents learn how criminal minds work.'),
  T('monk', S, '🧼', 'Monk', 2002, EN, ['comedy', 'crime', 'mystery'], 'A detective with many phobias and a perfect memory.'),
  T('psych', S, '🍍', 'Psych', 2006, EN, ['comedy', 'mystery'], 'A sharp-eyed slacker pretends to be a psychic detective.'),
  T('castle', S, '✒️', 'Castle', 2009, EN, ['crime', 'mystery', 'comedy'], 'A crime novelist tags along with a New York detective.'),
  T('white-collar', S, '🎩', 'White Collar', 2009, EN, ['crime', 'comedy'], 'A charming con artist helps the FBI catch other crooks.'),
  T('ncis', S, '⚓', 'NCIS', 2003, EN, ['crime', 'action'], 'A naval crime team solves cases with dry humour.'),
  T('the-blacklist', S, '🎩', 'The Blacklist', 2013, EN, ['crime', 'thriller'], 'A wanted mastermind offers to help the FBI, on his terms.'),
  T('prison-break', S, '🗺️', 'Prison Break', 2005, EN, ['action', 'crime', 'thriller'], 'A man gets himself locked up to break his brother out.'),
  T('reacher', S, '👊', 'Reacher', 2022, EN, ['action', 'crime'], 'A giant drifter keeps walking into small-town conspiracies.'),
  T('the-diplomat', S, '🏛️', 'The Diplomat', 2023, EN, ['drama', 'thriller'], 'A new US ambassador to the UK faces a crisis on day one.'),

  // ---------------------------------------------------------------- English series: spy
  T('slow-horses', S, '🐎', 'Slow Horses', 2022, EN, ['spy', 'thriller', 'comedy'], 'Disgraced MI5 agents stuck in a dead-end office.'),
  T('the-night-agent', S, '☎️', 'The Night Agent', 2023, EN, ['spy', 'thriller', 'action'], 'An FBI agent on the night phone takes one crucial call.'),
  T('killing-eve', S, '🗡️', 'Killing Eve', 2018, EN, ['spy', 'thriller'], 'An MI6 analyst and an assassin become obsessed with each other.'),
  T('the-americans', S, '🇷🇺', 'The Americans', 2013, EN, ['spy', 'drama', 'historical'], 'Soviet spies pose as a normal family in 1980s America.'),
  T('homeland', S, '🕵️', 'Homeland', 2011, EN, ['spy', 'thriller'], 'A CIA officer suspects a returning hero is not what he seems.'),
  T('twenty-four', S, '⏱️', '24', 2001, EN, ['spy', 'action', 'thriller'], 'One agent, one very long day, told in real time.'),
  T('jack-ryan', S, '🎖️', "Tom Clancy's Jack Ryan", 2018, EN, ['spy', 'action'], 'A CIA analyst gets pulled out from behind his desk.'),
  T('the-night-manager', S, '🏨', 'The Night Manager', 2016, EN, ['spy', 'thriller'], 'A hotel night manager goes undercover against an arms dealer.'),
  T('alias', S, '👩‍🎤', 'Alias', 2001, EN, ['spy', 'action'], 'A student leads a double life as a secret agent.'),
  T('chuck', S, '🖥️', 'Chuck', 2007, EN, ['spy', 'comedy', 'action'], 'An electronics-store nerd downloads government secrets.'),
  T('burn-notice', S, '🔥', 'Burn Notice', 2007, EN, ['spy', 'action'], 'A dropped spy stranded in Miami helps people in trouble.'),
  T('the-recruit', S, '📁', 'The Recruit', 2022, EN, ['spy', 'comedy'], 'A rookie CIA lawyer stumbles into a global mess.'),
  T('citadel', S, '🌐', 'Citadel', 2023, EN, ['spy', 'action'], 'Two agents with wiped memories are pulled back into the game.'),
  T('andor', S, '🌌', 'Andor', 2022, EN, ['scifi', 'spy', 'drama'], 'A thief becomes a rebel in the early days of the resistance.'),

  // ---------------------------------------------------------------- English series: sci-fi, fantasy, horror
  T('stranger-things', S, '🚲', 'Stranger Things', 2016, EN, ['scifi', 'horror', 'drama'], 'Kids on bikes, a missing friend and a very strange town.'),
  T('wednesday', S, '🖤', 'Wednesday', 2022, EN, ['mystery', 'comedy', 'fantasy'], 'A deadpan teen solves mysteries at a school for outcasts.'),
  T('severance', S, '🧊', 'Severance', 2022, EN, ['scifi', 'thriller', 'mystery'], 'Office workers whose work and home memories are split.'),
  T('shogun', S, '🏯', 'Shōgun', 2024, EN, ['historical', 'drama'], 'A shipwrecked English pilot is caught in feudal Japan’s power games.'),
  T('fallout', S, '☢️', 'Fallout', 2024, EN, ['scifi', 'action', 'comedy'], 'A cheerful vault dweller steps out into a wild wasteland.'),
  T('three-body-problem', S, '🌌', '3 Body Problem', 2024, EN, ['scifi', 'mystery'], 'Scientists face a puzzle that reaches far beyond Earth.'),
  T('the-mandalorian', S, '🪖', 'The Mandalorian', 2019, EN, ['scifi', 'action'], 'A lone bounty hunter and a tiny, powerful green child.'),
  T('the-last-of-us', S, '🍄', 'The Last of Us', 2023, EN, ['horror', 'drama', 'scifi'], 'A smuggler escorts a teen across a ruined America.'),
  T('haunting-of-hill-house', S, '🏚️', 'The Haunting of Hill House', 2018, EN, ['horror', 'drama', 'family'], 'Grown siblings still haunted by the house they grew up in.'),
  T('midnight-mass', S, '⛪', 'Midnight Mass', 2021, EN, ['horror', 'drama'], 'A charismatic priest arrives on a remote island.'),
  T('lost', S, '✈️', 'Lost', 2004, EN, ['mystery', 'scifi', 'drama'], 'Plane-crash survivors on an island with many secrets.'),
  T('x-files', S, '👽', 'The X-Files', 1993, EN, ['scifi', 'mystery'], 'Two FBI agents: one believer, one sceptic.'),
  T('buffy', S, '🧄', 'Buffy the Vampire Slayer', 1997, EN, ['fantasy', 'horror', 'comedy'], 'A high schooler balances homework with fighting vampires.'),
  T('doctor-who', S, '🟦', 'Doctor Who', 2005, EN, ['scifi', 'family'], 'A time traveller in a blue police box, with a new face now and then.'),
  T('black-mirror', S, '📱', 'Black Mirror', 2011, EN, ['scifi', 'thriller'], 'Standalone stories about technology gone slightly wrong.'),
  T('the-expanse', S, '🚀', 'The Expanse', 2015, EN, ['scifi', 'mystery'], 'A missing woman sparks trouble across a colonised solar system.'),
  T('foundation', S, '🪐', 'Foundation', 2021, EN, ['scifi', 'drama'], 'A mathematician predicts the fall of a galactic empire.'),
  T('silo', S, '🕳️', 'Silo', 2023, EN, ['scifi', 'mystery'], 'Thousands live in an underground silo. Why?'),
  T('rings-of-power', S, '💍', 'The Lord of the Rings: The Rings of Power', 2022, EN, ['fantasy', 'action'], 'Middle-earth, thousands of years before the Fellowship.'),
  T('wandavision', S, '📺', 'WandaVision', 2021, EN, ['fantasy', 'comedy', 'mystery'], 'Two superheroes living in a suspiciously perfect sitcom.'),
  T('loki', S, '🔱', 'Loki', 2021, EN, ['fantasy', 'scifi', 'comedy'], 'The god of mischief is caught by a time-policing agency.'),
  T('umbrella-academy', S, '☂️', 'The Umbrella Academy', 2019, EN, ['scifi', 'fantasy', 'family'], 'Estranged superpowered siblings reunite to stop the end of the world.'),
  T('supernatural', S, '🚗', 'Supernatural', 2005, EN, ['horror', 'fantasy'], 'Two brothers drive across America hunting monsters.'),
  T('heroes', S, '🌀', 'Heroes', 2006, EN, ['scifi', 'drama'], 'Ordinary people around the world discover powers.'),
  T('fringe', S, '🧪', 'Fringe', 2008, EN, ['scifi', 'mystery'], 'An FBI unit investigates science at its strangest edges.'),
  T('firefly', S, '🛸', 'Firefly', 2002, EN, ['scifi', 'action'], 'A ragtag crew flies a scrappy ship on the edge of space.'),
  T('star-trek-tng', S, '🖖', 'Star Trek: The Next Generation', 1987, EN, ['scifi'], 'The starship Enterprise explores, negotiates and wonders.'),
  T('the-walking-dead', S, '🧟', 'The Walking Dead', 2010, EN, ['horror', 'action', 'drama'], 'Survivors band together after the dead start walking.'),
  T('one-piece-live', S, '🏴‍☠️', 'One Piece', 2023, EN, ['fantasy', 'action', 'comedy'], 'A rubbery pirate and his crew chase the ultimate treasure.'),
  T('arcane', S, '⚙️', 'Arcane', 2021, EN, ['animation', 'fantasy', 'action'], 'Two sisters on opposite sides of a divided city.'),
  T('avatar-last-airbender', S, '🌪️', 'Avatar: The Last Airbender', 2005, EN, ['animation', 'fantasy', 'family'], 'A young monk must master all four elements to bring peace.'),

  // ---------------------------------------------------------------- English series: reality and documentary
  T('great-british-bake-off', S, '🍰', 'The Great British Bake Off', 2010, EN, ['reality'], 'Amateur bakers, a big tent and very polite drama.'),
  T('queer-eye', S, '💇', 'Queer Eye', 2018, EN, ['reality'], 'Five experts help people feel good about their lives.'),
  T('masterchef-australia', S, '👩‍🍳', 'MasterChef Australia', 2009, EN, ['reality'], 'Home cooks compete in the kindest cooking contest going.'),
  T('shark-tank', S, '🦈', 'Shark Tank', 2009, EN, ['reality'], 'Entrepreneurs pitch their ideas to tough investors.'),
  T('the-amazing-race', S, '🗺️', 'The Amazing Race', 2001, EN, ['reality'], 'Teams of two race around the world against the clock.'),
  T('survivor', S, '🔥', 'Survivor', 2000, EN, ['reality'], 'Strangers on an island outwit and outlast each other.'),
  T('nailed-it', S, '🧁', 'Nailed It!', 2018, EN, ['reality', 'comedy'], 'Very average bakers attempt very ambitious cakes.'),
  T('indian-matchmaking', S, '💍', 'Indian Matchmaking', 2020, EN, ['reality', 'romance'], 'A matchmaker helps Indian and diaspora singles find a match.'),
  T('planet-earth', S, '🌍', 'Planet Earth', 2006, EN, ['documentary'], 'The planet’s wildest places, filmed like never before.'),
  T('planet-earth-2', S, '🐆', 'Planet Earth II', 2016, EN, ['documentary'], 'Islands, jungles and cities, seen from the wild side.'),
  T('our-planet', S, '🌿', 'Our Planet', 2019, EN, ['documentary'], 'The natural world and how we can protect it.'),
  T('the-last-dance', S, '🏀', 'The Last Dance', 2020, EN, ['documentary', 'sports'], 'Michael Jordan and the 1990s Chicago Bulls dynasty.'),
  T('drive-to-survive', S, '🏎️', 'Formula 1: Drive to Survive', 2019, EN, ['documentary', 'sports'], 'Behind the scenes of a Formula 1 season.'),

  // ---------------------------------------------------------------- English films: spy
  T('goldeneye', M, '🛰️', 'GoldenEye', 1995, EN, ['spy', 'action'], 'Bond chases a stolen satellite weapon across Russia.'),
  T('casino-royale', M, '♠️', 'Casino Royale', 2006, EN, ['spy', 'action'], 'A newly promoted Bond faces a high-stakes card game.'),
  T('skyfall', M, '🦅', 'Skyfall', 2012, EN, ['spy', 'action'], 'Bond protects M when her past comes back.'),
  T('no-time-to-die', M, '⏳', 'No Time to Die', 2021, EN, ['spy', 'action'], 'Bond is pulled out of retirement one final time.'),
  T('mission-impossible', M, '🎭', 'Mission: Impossible', 1996, EN, ['spy', 'action'], 'An agent framed for betrayal must clear his name.'),
  T('mi-fallout', M, '🚁', 'Mission: Impossible – Fallout', 2018, EN, ['spy', 'action'], 'Helicopters, cliffs and a race to stop stolen plutonium.'),
  T('mi-dead-reckoning', M, '🚂', 'Mission: Impossible – Dead Reckoning Part One', 2023, EN, ['spy', 'action'], 'The IMF team takes on a rogue artificial intelligence.'),
  T('bourne-identity', M, '🧭', 'The Bourne Identity', 2002, EN, ['spy', 'action', 'thriller'], 'A man with no memory and deadly skills looks for answers.'),
  T('bourne-ultimatum', M, '🏃', 'The Bourne Ultimatum', 2007, EN, ['spy', 'action', 'thriller'], 'Bourne closes in on the people who made him.'),
  T('kingsman', M, '☂️', 'Kingsman: The Secret Service', 2014, EN, ['spy', 'action', 'comedy'], 'A street kid is trained by a very well-dressed spy agency.'),
  T('tinker-tailor', M, '♟️', 'Tinker Tailor Soldier Spy', 2011, EN, ['spy', 'thriller'], 'A quiet spymaster hunts a mole inside British intelligence.'),
  T('bridge-of-spies', M, '🌉', 'Bridge of Spies', 2015, EN, ['spy', 'historical', 'drama'], 'A lawyer negotiates a Cold War prisoner swap.'),
  T('spy-2015', M, '🕶️', 'Spy', 2015, EN, ['spy', 'comedy', 'action'], 'A desk-bound CIA analyst finally goes into the field.'),
  T('argo', M, '🎬', 'Argo', 2012, EN, ['spy', 'thriller', 'historical'], 'A fake film production becomes a daring rescue plan.'),

  // ---------------------------------------------------------------- English films: sci-fi and fantasy
  T('dune', M, '🏜️', 'Dune', 2021, EN, ['scifi', 'action'], 'A noble family takes over the most valuable desert planet.'),
  T('dune-part-two', M, '🪱', 'Dune: Part Two', 2024, EN, ['scifi', 'action'], 'Paul joins the desert people and faces his destiny.'),
  T('interstellar', M, '🌌', 'Interstellar', 2014, EN, ['scifi', 'drama', 'family'], 'Astronauts travel through a wormhole to save humanity.'),
  T('inception', M, '🌀', 'Inception', 2010, EN, ['scifi', 'action', 'thriller'], 'A team of thieves plants an idea inside a dream.'),
  T('the-matrix', M, '💊', 'The Matrix', 1999, EN, ['scifi', 'action'], 'A hacker learns the world is not what it seems.'),
  T('jurassic-park', M, '🦖', 'Jurassic Park', 1993, EN, ['scifi', 'action', 'family'], 'A theme park with real dinosaurs. What could go wrong?'),
  T('back-to-the-future', M, '⚡', 'Back to the Future', 1985, EN, ['scifi', 'comedy', 'family'], 'A teen in a time-travelling car meets his parents young.'),
  T('et', M, '🚲', 'E.T. the Extra-Terrestrial', 1982, EN, ['scifi', 'family'], 'A boy hides a lost alien and helps him get home.'),
  T('arrival', M, '🐙', 'Arrival', 2016, EN, ['scifi', 'drama', 'mystery'], 'A linguist tries to talk with visitors from space.'),
  T('the-martian', M, '🥔', 'The Martian', 2015, EN, ['scifi', 'drama'], 'A stranded astronaut grows potatoes on Mars to survive.'),
  T('gravity', M, '🛰️', 'Gravity', 2013, EN, ['scifi', 'thriller'], 'Two astronauts adrift after debris destroys their shuttle.'),
  T('avatar', M, '🌿', 'Avatar', 2009, EN, ['scifi', 'action', 'fantasy'], 'A soldier bonds with the people of the moon Pandora.'),
  T('blade-runner-2049', M, '🌃', 'Blade Runner 2049', 2017, EN, ['scifi', 'mystery'], 'A replicant hunter uncovers a long-buried secret.'),
  T('eeaao', M, '🥯', 'Everything Everywhere All at Once', 2022, EN, ['scifi', 'comedy', 'family'], 'A laundromat owner jumps across the multiverse.'),
  T('star-wars', M, '⭐', 'Star Wars', 1977, EN, ['scifi', 'fantasy', 'action'], 'A farm boy joins a rebellion in a galaxy far, far away.'),
  T('terminator-2', M, '🤖', 'Terminator 2: Judgment Day', 1991, EN, ['scifi', 'action'], 'A cyborg protects the boy who will lead the future.'),
  T('independence-day', M, '🛸', 'Independence Day', 1996, EN, ['scifi', 'action'], 'Humanity fights back against a giant alien invasion.'),
  T('men-in-black', M, '🕶️', 'Men in Black', 1997, EN, ['scifi', 'comedy', 'action'], 'Secret agents keep an eye on aliens living on Earth.'),
  T('lotr-fellowship', M, '💍', 'The Lord of the Rings: The Fellowship of the Ring', 2001, EN, ['fantasy', 'action'], 'A hobbit sets out to destroy a very dangerous ring.'),
  T('harry-potter-1', M, '⚡', "Harry Potter and the Philosopher's Stone", 2001, EN, ['fantasy', 'family'], 'An orphan learns he is a wizard and heads to Hogwarts.'),
  T('wicked', M, '🧙‍♀️', 'Wicked', 2024, EN, ['music', 'fantasy'], 'Two very different witches meet at school in Oz.'),

  // ---------------------------------------------------------------- English films: horror
  T('the-conjuring', M, '🕯️', 'The Conjuring', 2013, EN, ['horror'], 'Paranormal investigators help a family in a haunted farmhouse.'),
  T('get-out', M, '☕', 'Get Out', 2017, EN, ['horror', 'thriller'], 'Meeting the girlfriend’s parents gets very unsettling.'),
  T('a-quiet-place', M, '🤫', 'A Quiet Place', 2018, EN, ['horror', 'scifi', 'family'], 'A family survives by never making a sound.'),
  T('it-2017', M, '🎈', 'It', 2017, EN, ['horror'], 'A group of kids face a shape-shifting clown in their town.'),
  T('the-sixth-sense', M, '👁️', 'The Sixth Sense', 1999, EN, ['horror', 'mystery', 'drama'], 'A child psychologist helps a boy who sees ghosts.'),
  T('the-shining', M, '🪓', 'The Shining', 1980, EN, ['horror'], 'A winter caretaker job at an empty mountain hotel.'),
  T('scream', M, '📞', 'Scream', 1996, EN, ['horror', 'mystery'], 'A masked caller who knows every horror-film rule.'),
  T('insidious', M, '🚪', 'Insidious', 2010, EN, ['horror'], 'A boy slips into a coma and something follows him back.'),
  T('the-others', M, '🕯️', 'The Others', 2001, EN, ['horror', 'mystery'], 'A mother and her children in a foggy, silent mansion.'),
  T('nope', M, '☁️', 'Nope', 2022, EN, ['horror', 'scifi'], 'Siblings on a ranch spot something strange in the clouds.'),
  T('the-ring', M, '📼', 'The Ring', 2002, EN, ['horror', 'mystery'], 'A cursed videotape and seven days to solve it.'),
  T('coraline', M, '🪡', 'Coraline', 2009, EN, ['animation', 'horror', 'fantasy'], 'A girl finds a door to a too-perfect other home.'),

  // ---------------------------------------------------------------- English films: romance and rom-com
  T('notting-hill', M, '📚', 'Notting Hill', 1999, EN, ['romance', 'comedy'], 'A London bookseller falls for a famous film star.'),
  T('sleepless-in-seattle', M, '📻', 'Sleepless in Seattle', 1993, EN, ['romance', 'comedy'], 'A radio call-in show sparks a cross-country romance.'),
  T('youve-got-mail', M, '💌', "You've Got Mail", 1998, EN, ['romance', 'comedy'], 'Business rivals by day, secret email pen pals by night.'),
  T('titanic', M, '🚢', 'Titanic', 1997, EN, ['romance', 'historical', 'drama'], 'A love story aboard the ship everyone knows.'),
  T('the-notebook', M, '📓', 'The Notebook', 2004, EN, ['romance', 'drama'], 'A summer love story read aloud, years later.'),
  T('crazy-rich-asians', M, '💎', 'Crazy Rich Asians', 2018, EN, ['romance', 'comedy', 'family'], 'Meeting the boyfriend’s family turns out to be a big deal.'),
  T('la-la-land', M, '🎹', 'La La Land', 2016, EN, ['romance', 'music'], 'A jazz pianist and an actor chase dreams in LA.'),
  T('pride-and-prejudice', M, '🌧️', 'Pride & Prejudice', 2005, EN, ['romance', 'historical'], 'Elizabeth Bennet meets the very proud Mr Darcy.'),
  T('about-time', M, '⏰', 'About Time', 2013, EN, ['romance', 'fantasy', 'family'], 'A young man can time travel and uses it for love.'),
  T('the-proposal', M, '💼', 'The Proposal', 2009, EN, ['romance', 'comedy'], 'A boss fakes an engagement to her assistant to stay in the US.'),
  T('ten-things', M, '📝', '10 Things I Hate About You', 1999, EN, ['romance', 'comedy'], 'A high-school romance with a Shakespeare twist.'),
  T('to-all-the-boys', M, '💌', "To All the Boys I've Loved Before", 2018, EN, ['romance', 'comedy'], 'Secret love letters get sent out by mistake.'),
  T('past-lives', M, '🌆', 'Past Lives', 2023, EN, ['romance', 'drama'], 'Childhood friends reconnect decades later across continents.'),
  T('before-sunrise', M, '🌅', 'Before Sunrise', 1995, EN, ['romance', 'drama'], 'Two strangers spend one night walking and talking in Vienna.'),
  T('the-holiday', M, '🏡', 'The Holiday', 2006, EN, ['romance', 'comedy'], 'Two women swap homes for Christmas and find surprises.'),
  T('the-big-sick', M, '🏥', 'The Big Sick', 2017, EN, ['romance', 'comedy', 'family'], 'A Pakistani-American comic, his girlfriend and both families.'),
  T('mississippi-masala', M, '🌶️', 'Mississippi Masala', 1991, EN, ['romance', 'drama'], 'An Indian-Ugandan woman falls for a man in the American South.'),
  T('roman-holiday', M, '🛵', 'Roman Holiday', 1953, EN, ['romance', 'comedy'], 'A princess escapes for one carefree day in Rome.'),

  // ---------------------------------------------------------------- English films: comedy, family, music
  T('home-alone', M, '🏠', 'Home Alone', 1990, EN, ['comedy', 'family'], 'A boy left behind at Christmas defends his house.'),
  T('mrs-doubtfire', M, '👵', 'Mrs. Doubtfire', 1993, EN, ['comedy', 'family'], 'A dad becomes a Scottish nanny to see his kids.'),
  T('groundhog-day', M, '⏰', 'Groundhog Day', 1993, EN, ['comedy', 'fantasy', 'romance'], 'A grumpy weatherman relives the same day again and again.'),
  T('legally-blonde', M, '💗', 'Legally Blonde', 2001, EN, ['comedy'], 'A sorority star surprises everyone at Harvard Law.'),
  T('mean-girls', M, '👛', 'Mean Girls', 2004, EN, ['comedy'], 'A new girl navigates a high-school social jungle.'),
  T('grand-budapest-hotel', M, '🏨', 'The Grand Budapest Hotel', 2014, EN, ['comedy', 'crime'], 'A legendary concierge and his loyal lobby boy.'),
  T('knives-out', M, '🔪', 'Knives Out', 2019, EN, ['mystery', 'comedy', 'crime'], 'A detective untangles a rich family’s mystery.'),
  T('glass-onion', M, '🧅', 'Glass Onion', 2022, EN, ['mystery', 'comedy'], 'A tech billionaire’s island getaway turns into a puzzle.'),
  T('barbie', M, '🩷', 'Barbie', 2023, EN, ['comedy', 'fantasy'], 'Barbie leaves her perfect world for the real one.'),
  T('paddington-2', M, '🧸', 'Paddington 2', 2017, EN, ['family', 'comedy'], 'A polite bear from Peru hunts for a stolen pop-up book.'),
  T('school-of-rock', M, '🎸', 'School of Rock', 2003, EN, ['comedy', 'music', 'family'], 'A fake substitute teacher turns a class into a band.'),
  T('the-intern', M, '👓', 'The Intern', 2015, EN, ['comedy', 'drama'], 'A 70-year-old intern joins a fashion start-up.'),
  T('jumanji', M, '🎲', 'Jumanji', 1995, EN, ['fantasy', 'family', 'action'], 'A board game that brings the jungle into your house.'),
  T('bend-it-like-beckham', M, '⚽', 'Bend It Like Beckham', 2002, EN, ['sports', 'comedy', 'family'], 'A British Punjabi girl secretly joins a football team.'),
  T('the-truman-show', M, '📺', 'The Truman Show', 1998, EN, ['drama', 'comedy', 'scifi'], 'A man slowly realises his whole life is on TV.'),
  T('sound-of-music', M, '⛰️', 'The Sound of Music', 1965, EN, ['music', 'family', 'historical'], 'A governess, seven children and the Austrian Alps.'),
  T('mary-poppins', M, '☂️', 'Mary Poppins', 1964, EN, ['music', 'family', 'fantasy'], 'A magical nanny floats in on the east wind.'),
  T('mamma-mia', M, '🏝️', 'Mamma Mia!', 2008, EN, ['music', 'comedy', 'romance'], 'A bride-to-be invites three possible dads to her wedding.'),

  // ---------------------------------------------------------------- English films: drama, action, crime, sport
  T('forrest-gump', M, '🪶', 'Forrest Gump', 1994, EN, ['drama', 'romance', 'historical'], 'A kind man drifts through decades of American history.'),
  T('shawshank', M, '🔨', 'The Shawshank Redemption', 1994, EN, ['drama', 'crime'], 'Friendship and hope inside a prison over many years.'),
  T('pursuit-of-happyness', M, '💼', 'The Pursuit of Happyness', 2006, EN, ['drama', 'family'], 'A struggling dad chases a stockbroker internship.'),
  T('slumdog-millionaire', M, '💰', 'Slumdog Millionaire', 2008, EN, ['drama', 'romance'], 'A Mumbai teen on a quiz show, every answer a memory.'),
  T('life-of-pi', M, '🐅', 'Life of Pi', 2012, EN, ['drama', 'fantasy'], 'A boy from Pondicherry adrift at sea with a tiger.'),
  T('lion', M, '🗺️', 'Lion', 2016, EN, ['drama', 'family'], 'A man searches for the Indian home he lost as a child.'),
  T('the-social-network', M, '💻', 'The Social Network', 2010, EN, ['drama'], 'The messy, lawsuit-filled founding of Facebook.'),
  T('the-kings-speech', M, '🎙️', "The King's Speech", 2010, EN, ['historical', 'drama'], 'A king works with a speech coach to find his voice.'),
  T('hidden-figures', M, '🧮', 'Hidden Figures', 2016, EN, ['historical', 'drama'], 'Three Black women mathematicians behind NASA’s launches.'),
  T('dead-poets-society', M, '📜', 'Dead Poets Society', 1989, EN, ['drama'], 'An English teacher inspires boys to seize the day.'),
  T('oppenheimer', M, '💥', 'Oppenheimer', 2023, EN, ['historical', 'drama', 'thriller'], 'The physicist behind the first atomic bomb.'),
  T('gladiator', M, '🏛️', 'Gladiator', 2000, EN, ['historical', 'action'], 'A betrayed Roman general fights his way back.'),
  T('the-dark-knight', M, '🦇', 'The Dark Knight', 2008, EN, ['action', 'crime'], 'Batman faces a chaotic new enemy in Gotham.'),
  T('avengers-endgame', M, '🛡️', 'Avengers: Endgame', 2019, EN, ['action', 'scifi'], 'The Avengers regroup for one last big mission.'),
  T('top-gun-maverick', M, '✈️', 'Top Gun: Maverick', 2022, EN, ['action', 'drama'], 'A veteran pilot trains a new crew for an impossible run.'),
  T('mad-max-fury-road', M, '🚛', 'Mad Max: Fury Road', 2015, EN, ['action', 'scifi'], 'One long, loud chase across a desert wasteland.'),
  T('black-panther', M, '🐾', 'Black Panther', 2018, EN, ['action', 'fantasy'], 'A new king defends the hidden nation of Wakanda.'),
  T('murder-orient-express', M, '🚂', 'Murder on the Orient Express', 2017, EN, ['mystery', 'crime'], 'Poirot, a snowbound train and a carriage full of suspects.'),
  T('sherlock-holmes-2009', M, '🎻', 'Sherlock Holmes', 2009, EN, ['mystery', 'action'], 'Holmes and Watson brawl and deduce through Victorian London.'),
  T('oceans-eleven', M, '🎰', "Ocean's Eleven", 2001, EN, ['crime', 'comedy'], 'A smooth crew plans to rob three Las Vegas vaults at once.'),
  T('catch-me-if-you-can', M, '✈️', 'Catch Me If You Can', 2002, EN, ['crime', 'drama'], 'A teen con artist and the FBI agent chasing him.'),
  T('inside-man', M, '🏦', 'Inside Man', 2006, EN, ['crime', 'thriller'], 'A bank heist where nothing is quite what it looks like.'),
  T('rocky', M, '🥊', 'Rocky', 1976, EN, ['sports', 'drama'], 'A small-time boxer gets a shot at the title.'),
  T('remember-the-titans', M, '🏈', 'Remember the Titans', 2000, EN, ['sports', 'drama', 'historical'], 'A newly integrated school team learns to play as one.'),
  T('moneyball', M, '⚾', 'Moneyball', 2011, EN, ['sports', 'drama'], 'A baseball manager bets on statistics over scouts.'),
  T('ford-v-ferrari', M, '🏁', 'Ford v Ferrari', 2019, EN, ['sports', 'drama', 'historical'], 'Engineers and a driver take on Le Mans.'),

  // ---------------------------------------------------------------- English films: animation and documentary
  T('toy-story', M, '🤠', 'Toy Story', 1995, EN, ['animation', 'family', 'comedy'], 'A cowboy doll meets a new space-ranger toy.'),
  T('up', M, '🎈', 'Up', 2009, EN, ['animation', 'family'], 'An old man ties balloons to his house and flies away.'),
  T('inside-out', M, '😊', 'Inside Out', 2015, EN, ['animation', 'family', 'comedy'], 'The emotions inside one girl’s head during a big move.'),
  T('inside-out-2', M, '😬', 'Inside Out 2', 2024, EN, ['animation', 'family', 'comedy'], 'Teenage years bring brand-new emotions to headquarters.'),
  T('coco', M, '💀', 'Coco', 2017, EN, ['animation', 'music', 'family'], 'A boy who loves music visits the Land of the Dead.'),
  T('the-lion-king', M, '🦁', 'The Lion King', 1994, EN, ['animation', 'family', 'music'], 'A young lion must return to claim his place.'),
  T('frozen', M, '❄️', 'Frozen', 2013, EN, ['animation', 'music', 'family'], 'Two royal sisters and a kingdom stuck in winter.'),
  T('moana', M, '🌊', 'Moana', 2016, EN, ['animation', 'music', 'family'], 'A chief’s daughter sails the ocean to save her island.'),
  T('ratatouille', M, '👨‍🍳', 'Ratatouille', 2007, EN, ['animation', 'family', 'comedy'], 'A rat with big dreams cooks in a Paris kitchen.'),
  T('shrek', M, '🧅', 'Shrek', 2001, EN, ['animation', 'comedy', 'family'], 'A grumpy ogre goes on a fairy-tale rescue mission.'),
  T('how-to-train-your-dragon', M, '🐉', 'How to Train Your Dragon', 2010, EN, ['animation', 'family', 'fantasy'], 'A Viking teen befriends the dragon he was meant to fight.'),
  T('kung-fu-panda', M, '🐼', 'Kung Fu Panda', 2008, EN, ['animation', 'comedy', 'action'], 'A noodle-loving panda is chosen as the Dragon Warrior.'),
  T('soul', M, '🎷', 'Soul', 2020, EN, ['animation', 'music', 'family'], 'A jazz teacher gets lost on the way to his big gig.'),
  T('spider-verse', M, '🕷️', 'Spider-Man: Into the Spider-Verse', 2018, EN, ['animation', 'action', 'family'], 'Miles Morales meets Spider-People from other worlds.'),
  T('wall-e', M, '🤖', 'WALL-E', 2008, EN, ['animation', 'scifi', 'family'], 'A lonely cleaning robot falls in love in space.'),
  T('encanto', M, '🦋', 'Encanto', 2021, EN, ['animation', 'music', 'family'], 'The only family member without a magic gift saves the day.'),
  T('free-solo', M, '🧗', 'Free Solo', 2018, EN, ['documentary', 'sports'], 'A climber attempts El Capitan with no ropes.'),
  T('social-dilemma', M, '📲', 'The Social Dilemma', 2020, EN, ['documentary'], 'Tech insiders explain how apps keep us scrolling.'),
  T('wont-you-be-my-neighbor', M, '🧶', "Won't You Be My Neighbor?", 2018, EN, ['documentary', 'family'], 'The gentle life of children’s TV host Fred Rogers.'),
  T('searching-for-sugar-man', M, '🎸', 'Searching for Sugar Man', 2012, EN, ['documentary', 'music'], 'Two fans hunt for a forgotten singer from Detroit.'),
  T('senna', M, '🏎️', 'Senna', 2010, EN, ['documentary', 'sports'], 'The racing life of Brazilian driver Ayrton Senna.'),

  // ---------------------------------------------------------------- Comedy specials
  T('zakir-haq-se-single', X, '🎤', 'Zakir Khan: Haq Se Single', 2017, HI, ['standup', 'comedy'], 'Stories of being proudly, hopefully single.'),
  T('zakir-tathastu', X, '🎤', 'Zakir Khan: Tathastu', 2022, HI, ['standup', 'comedy'], 'Warm stories about growing up, family and wishes.'),
  T('vir-das-abroad-understanding', X, '🎤', 'Vir Das: Abroad Understanding', 2017, EN, ['standup', 'comedy'], 'India meets America in a two-city stand-up set.'),
  T('vir-das-landing', X, '🎤', 'Vir Das: Landing', 2022, EN, ['standup', 'comedy'], 'Thoughts on home, fame and belonging.'),
  T('kenny-sebastian-tmipitr', X, '🎤', 'Kenny Sebastian: The Most Interesting Person in the Room', 2020, EN, ['standup', 'comedy'], 'Gentle observational comedy about trying to be interesting.'),
  T('bassi-bas-kar-bassi', X, '🎤', 'Anubhav Singh Bassi: Bas Kar Bassi', 2023, HI, ['standup', 'comedy'], 'Long, silly stories from law school and life.'),
  T('biswa-mast-aadmi', X, '🎤', 'Biswa Kalyan Rath: Biswa Mast Aadmi', 2017, HI, ['standup', 'comedy'], 'Deadpan takes on everyday Indian life.'),
  T('kanan-keep-it-real', X, '🎤', 'Kanan Gill: Keep It Real', 2017, EN, ['standup', 'comedy'], 'A letter to his younger self, and some honest laughs.'),
  T('hasan-homecoming-king', X, '🎤', 'Hasan Minhaj: Homecoming King', 2017, EN, ['standup', 'comedy', 'family'], 'Growing up Indian-American, told like a warm story.'),
  T('hasan-kings-jester', X, '🎤', "Hasan Minhaj: The King's Jester", 2022, EN, ['standup', 'comedy'], 'Fame, family and the cost of the spotlight.'),
  T('trevor-son-of-patricia', X, '🎤', 'Trevor Noah: Son of Patricia', 2018, EN, ['standup', 'comedy'], 'Stories of accents, travel and his mum.'),
  T('trevor-afraid-of-the-dark', X, '🎤', 'Trevor Noah: Afraid of the Dark', 2017, EN, ['standup', 'comedy'], 'Accents, travels and life between countries.'),
  T('mulaney-comeback-kid', X, '🎤', 'John Mulaney: The Comeback Kid', 2015, EN, ['standup', 'comedy'], 'Precise, playful stories about childhood and adulthood.'),
  T('mulaney-kid-gorgeous', X, '🎤', 'John Mulaney: Kid Gorgeous at Radio City', 2018, EN, ['standup', 'comedy'], 'School assemblies, college and other absurdities.'),
  T('bargatze-tennessee-kid', X, '🎤', 'Nate Bargatze: The Tennessee Kid', 2019, EN, ['standup', 'comedy'], 'Squeaky-clean, slow-burn stories from the South.'),
  T('bargatze-hello-world', X, '🎤', 'Nate Bargatze: Hello World', 2023, EN, ['standup', 'comedy'], 'Everyday confusion delivered with a straight face.'),
  T('tomlinson-quarter-life-crisis', X, '🎤', 'Taylor Tomlinson: Quarter-Life Crisis', 2020, EN, ['standup', 'comedy'], 'Being in your twenties and figuring it all out.'),
  T('tomlinson-look-at-you', X, '🎤', 'Taylor Tomlinson: Look at You', 2022, EN, ['standup', 'comedy'], 'Honest, sharp jokes about growing up and moving on.'),
  T('gaffigan-mr-universe', X, '🎤', 'Jim Gaffigan: Mr. Universe', 2012, EN, ['standup', 'comedy', 'family'], 'Family life, laziness and a big love of food.'),
  T('seinfeld-23-hours', X, '🎤', 'Jerry Seinfeld: 23 Hours to Kill', 2020, EN, ['standup', 'comedy'], 'Classic observational comedy on everyday life.'),
  T('birbiglia-the-new-one', X, '🎤', 'Mike Birbiglia: The New One', 2019, EN, ['standup', 'comedy', 'family'], 'A reluctant man becomes a dad, told as a story.'),
  T('russell-peters-outsourced', X, '🎤', 'Russell Peters: Outsourced', 2006, EN, ['standup', 'comedy'], 'Accents and culture clashes from around the world.'),

  // ---------------------------------------------------------------- Hindi series
  T('panchayat', S, '🌾', 'Panchayat', 2020, HI, ['comedy', 'drama'], 'An engineering grad takes a job in a village office.'),
  T('kota-factory', S, '📚', 'Kota Factory', 2019, HI, ['drama'], 'Teens in the coaching capital prepare for big exams.'),
  T('scam-1992', S, '📈', 'Scam 1992', 2020, HI, ['drama', 'crime', 'historical'], 'The rise and fall of stock market star Harshad Mehta.'),
  T('the-family-man', S, '👨‍👩‍👧', 'The Family Man', 2019, HI, ['spy', 'action', 'comedy'], 'A middle-class dad who is secretly a top intelligence officer.'),
  T('special-ops', S, '🎯', 'Special Ops', 2020, HI, ['spy', 'thriller'], 'An officer tracks one man across years of attacks.'),
  T('paatal-lok', S, '🚓', 'Paatal Lok', 2020, HI, ['crime', 'thriller'], 'A tired Delhi cop lands a high-profile case.'),
  T('made-in-heaven', S, '💒', 'Made in Heaven', 2019, HI, ['drama', 'romance'], 'Two wedding planners and the secrets behind big weddings.'),
  T('heeramandi', S, '🏰', 'Heeramandi: The Diamond Bazaar', 2024, HI, ['historical', 'drama'], 'Power, rivalry and rebellion in pre-independence Lahore.'),
  T('gullak', S, '🏺', 'Gullak', 2019, HI, ['family', 'comedy'], 'Small-town family life told by the family piggy bank.'),
  T('tvf-pitchers', S, '💡', 'TVF Pitchers', 2015, HI, ['drama', 'comedy'], 'Four friends quit their jobs to start a start-up.'),
  T('aspirants', S, '📖', 'Aspirants', 2021, HI, ['drama'], 'Three friends and the tough road of civil-service exams.'),
  T('yeh-meri-family', S, '📼', 'Yeh Meri Family', 2018, HI, ['family', 'comedy'], 'A 12-year-old’s summer in the 1990s.'),
  T('little-things', S, '🌧️', 'Little Things', 2016, HI, ['romance', 'drama'], 'A Mumbai couple and the small moments of living together.'),
  T('rocket-boys', S, '🚀', 'Rocket Boys', 2022, HI, ['historical', 'drama'], 'Homi Bhabha, Vikram Sarabhai and India’s science dreams.'),
  T('farzi', S, '💵', 'Farzi', 2023, HI, ['crime', 'thriller'], 'A struggling artist starts printing perfect fake notes.'),
  T('the-railway-men', S, '🚉', 'The Railway Men', 2023, HI, ['historical', 'drama'], 'Railway workers save lives on the night of the Bhopal gas leak.'),
  T('kohrra', S, '🌫️', 'Kohrra', 2023, HI, ['crime', 'mystery'], 'Two cops investigate a case in foggy rural Punjab.'),
  T('dahaad', S, '🦁', 'Dahaad', 2023, HI, ['crime', 'thriller'], 'A small-town sub-inspector connects a string of cases.'),
  T('jubilee', S, '🎞️', 'Jubilee', 2023, HI, ['historical', 'drama', 'music'], 'The golden age of Bombay cinema and its ambitions.'),
  T('asur', S, '🔱', 'Asur', 2020, HI, ['crime', 'thriller', 'mystery'], 'Forensics meets mythology in a hunt for a killer.'),
  T('jamtara', S, '📞', 'Jamtara', 2020, HI, ['crime', 'drama'], 'Young phone scammers in a small Jharkhand town.'),
  T('flames', S, '🔥', 'Flames', 2018, HI, ['romance', 'comedy'], 'First love at a tuition centre.'),
  T('permanent-roommates', S, '🏠', 'Permanent Roommates', 2014, HI, ['romance', 'comedy'], 'A long-distance couple try living together.'),
  T('tripling', S, '🚙', 'TVF Tripling', 2016, HI, ['comedy', 'family'], 'Three grown siblings take a chaotic road trip.'),
  T('sapne-vs-everyone', S, '🎭', 'Sapne vs Everyone', 2023, HI, ['drama'], 'Two young men chase big dreams in Mumbai.'),
  T('mismatched', S, '💻', 'Mismatched', 2020, HI, ['romance', 'comedy'], 'A coder and a traditional-minded girl meet at a summer course.'),
  T('kaala-paani', S, '🏝️', 'Kaala Paani', 2023, HI, ['thriller', 'drama'], 'A mystery illness spreads across the Andaman Islands.'),
  T('guns-and-gulaabs', S, '🌹', 'Guns & Gulaabs', 2023, HI, ['crime', 'comedy'], 'Quirky small-town crooks in a very 1990s caper.'),
  T('bandish-bandits', S, '🎶', 'Bandish Bandits', 2020, HI, ['music', 'romance'], 'A classical singer and a pop star fall for each other.'),
  T('sunflower', S, '🌻', 'Sunflower', 2021, HI, ['comedy', 'mystery'], 'An odd mystery in a quirky Mumbai housing society.'),
  T('ghoul', S, '👹', 'Ghoul', 2018, HI, ['horror', 'thriller'], 'Something ancient awakens in a secret detention centre.'),
  T('typewriter', S, '⌨️', 'Typewriter', 2019, HI, ['horror', 'family', 'mystery'], 'Kids in Goa hunt ghosts in an old villa.'),
  T('bard-of-blood', S, '🗡️', 'Bard of Blood', 2019, HI, ['spy', 'thriller'], 'A former agent turned teacher returns for one mission.'),
  T('mukhbir', S, '🕵️', 'Mukhbir: The Story of a Spy', 2022, HI, ['spy', 'historical'], 'A young man goes undercover in 1960s Pakistan.'),
  T('citadel-honey-bunny', S, '🍯', 'Citadel: Honey Bunny', 2024, HI, ['spy', 'action'], 'A stuntman and an actor pulled into a spy world in the 90s.'),
  T('mahabharat', S, '🏹', 'Mahabharat', 1988, HI, ['historical', 'drama', 'fantasy'], 'The great epic, as a whole country watched on Sundays.'),
  T('ramayan', S, '🏹', 'Ramayan', 1987, HI, ['historical', 'drama', 'fantasy'], 'The classic epic that brought streets to a standstill.'),
  T('dekh-bhai-dekh', S, '🏠', 'Dekh Bhai Dekh', 1993, HI, ['comedy', 'family'], 'A big joint family and endless comic mix-ups.'),
  T('sarabhai-vs-sarabhai', S, '🛋️', 'Sarabhai vs Sarabhai', 2004, HI, ['comedy', 'family'], 'An upper-class mother-in-law versus her middle-class bahu.'),
  T('hum-paanch', S, '🖼️', 'Hum Paanch', 1995, HI, ['comedy', 'family'], 'A dad, five daughters and plenty of chaos.'),
  T('shaktimaan', S, '🌀', 'Shaktimaan', 1997, HI, ['action', 'fantasy', 'family'], 'India’s own superhero, spinning into action.'),
  T('byomkesh-bakshi', S, '🔍', 'Byomkesh Bakshi', 1993, HI, ['mystery', 'crime'], 'A calm Bengali truth-seeker solves Calcutta’s puzzles.'),
  T('malgudi-days', S, '🚂', 'Malgudi Days', 1986, HI, ['family', 'drama'], 'Gentle stories from a small fictional South Indian town.'),
  T('tmkoc', S, '🏘️', 'Taarak Mehta Ka Ooltah Chashmah', 2008, HI, ['comedy', 'family'], 'Life, festivals and fun in Gokuldham Society.'),
  T('khichdi', S, '🍲', 'Khichdi', 2002, HI, ['comedy', 'family'], 'A wonderfully clueless Gujarati joint family.'),
  T('office-office', S, '🗂️', 'Office Office', 2001, HI, ['comedy'], 'The common man versus government red tape.'),
  T('chhota-bheem', S, '💪', 'Chhota Bheem', 2008, HI, ['animation', 'family', 'action'], 'A strong, laddoo-loving boy protects his village.'),
  T('kbc', S, '💡', 'Kaun Banega Crorepati', 2000, HI, ['reality'], 'The quiz show where one answer can change a life.'),
  T('indian-idol', S, '🎤', 'Indian Idol', 2004, HI, ['reality', 'music'], 'Singers from across India compete for the title.'),
  T('shark-tank-india', S, '🦈', 'Shark Tank India', 2021, HI, ['reality'], 'Indian founders pitch to investors for funding.'),
  T('dance-india-dance', S, '💃', 'Dance India Dance', 2009, HI, ['reality', 'music'], 'Dancers from every style battle it out on stage.'),
  T('masterchef-india', S, '🍛', 'MasterChef India', 2010, HI, ['reality'], 'Home cooks from across India compete in the kitchen.'),
  T('comicstaan', S, '🎙️', 'Comicstaan', 2018, HI, ['reality', 'standup', 'comedy'], 'New stand-up comics compete, mentored by the pros.'),
  T('kapil-sharma-show', S, '🛋️', 'The Kapil Sharma Show', 2016, HI, ['comedy'], 'Celebrity guests, sketches and big family-style laughs.'),
  T('the-romantics', S, '💞', 'The Romantics', 2023, HI, ['documentary', 'music'], 'The Yash Chopra legacy and the Hindi film love story.'),
  T('angry-young-men', S, '✍️', 'Angry Young Men', 2024, HI, ['documentary'], 'Screenwriters Salim–Javed and the films they wrote.'),

  // ---------------------------------------------------------------- Hindi films: classics to 2000s
  T('mughal-e-azam', M, '👑', 'Mughal-e-Azam', 1960, HI, ['historical', 'romance'], 'A Mughal prince defies his emperor father for love.'),
  T('anand', M, '🌻', 'Anand', 1971, HI, ['drama'], 'A cheerful patient changes the life of his doctor.'),
  T('chupke-chupke', M, '🤫', 'Chupke Chupke', 1975, HI, ['comedy', 'family'], 'A professor pretends to be a driver to prank his in-laws.'),
  T('sholay', M, '🔫', 'Sholay', 1975, HI, ['action', 'drama'], 'Two friends hired to protect a village from a dacoit.'),
  T('golmaal-1979', M, '🥸', 'Gol Maal', 1979, HI, ['comedy'], 'A man invents a twin to keep his job.'),
  T('jaane-bhi-do-yaaro', M, '📷', 'Jaane Bhi Do Yaaro', 1983, HI, ['comedy', 'crime'], 'Two photographers stumble onto a huge scandal.'),
  T('mr-india', M, '⌚', 'Mr. India', 1987, HI, ['scifi', 'comedy', 'family'], 'A kind man finds a gadget that makes him invisible.'),
  T('jo-jeeta-wohi-sikandar', M, '🚴', 'Jo Jeeta Wohi Sikandar', 1992, HI, ['sports', 'romance', 'drama'], 'A carefree college boy and one big cycle race.'),
  T('andaz-apna-apna', M, '🤪', 'Andaz Apna Apna', 1994, HI, ['comedy'], 'Two slackers compete to woo an heiress.'),
  T('hahk', M, '🎊', 'Hum Aapke Hain Koun..!', 1994, HI, ['family', 'romance', 'music'], 'Two families, one wedding season, many songs.'),
  T('kabhi-haan-kabhi-naa', M, '🎸', 'Kabhi Haan Kabhi Naa', 1994, HI, ['romance', 'comedy'], 'A lovable loser in a Goa band chases his crush.'),
  T('ddlj', M, '🚂', 'Dilwale Dulhania Le Jayenge', 1995, HI, ['romance', 'family'], 'A train across Europe, then the mustard fields of Punjab.'),
  T('rangeela', M, '🌈', 'Rangeela', 1995, HI, ['romance', 'music'], 'A dancer dreams of film stardom in Mumbai.'),
  T('dil-to-pagal-hai', M, '💃', 'Dil To Pagal Hai', 1997, HI, ['romance', 'music'], 'A dance troupe and a love triangle.'),
  T('kkhh', M, '🏀', 'Kuch Kuch Hota Hai', 1998, HI, ['romance', 'family'], 'A widower’s daughter tries to reunite him with an old friend.'),
  T('satya', M, '🌆', 'Satya', 1998, HI, ['crime', 'drama'], 'A newcomer is drawn into Mumbai’s underworld.'),
  T('hum-saath-saath-hain', M, '👨‍👩‍👦‍👦', 'Hum Saath-Saath Hain', 1999, HI, ['family', 'drama'], 'A joint family tested when a wedge comes between brothers.'),
  T('hera-pheri', M, '☎️', 'Hera Pheri', 2000, HI, ['comedy'], 'Three broke men and one wrong-number phone call.'),
  T('kaho-naa-pyaar-hai', M, '🌊', 'Kaho Naa... Pyaar Hai', 2000, HI, ['romance', 'thriller'], 'A love story that jumps to New Zealand and back.'),
  T('mohabbatein', M, '🎻', 'Mohabbatein', 2000, HI, ['romance', 'music'], 'A music teacher brings love to a strict boys’ school.'),
  T('dil-chahta-hai', M, '🚗', 'Dil Chahta Hai', 2001, HI, ['comedy', 'drama', 'romance'], 'Three friends, Goa, and growing up.'),
  T('lagaan', M, '🏏', 'Lagaan', 2001, HI, ['sports', 'historical', 'drama'], 'A village bets everything on a cricket match.'),
  T('k3g', M, '🏰', 'Kabhi Khushi Kabhie Gham', 2001, HI, ['family', 'drama', 'romance'], 'A family split apart and the brother who brings it together.'),
  T('rhtdm', M, '🎸', 'Rehnaa Hai Terre Dil Mein', 2001, HI, ['romance'], 'A college rogue pretends to be someone else to win a girl.'),
  T('devdas', M, '🪔', 'Devdas', 2002, HI, ['romance', 'historical', 'drama'], 'A grand, tragic love story in dazzling sets.'),
  T('saathiya', M, '🚆', 'Saathiya', 2002, HI, ['romance', 'drama'], 'Two young people marry in secret and then face real life.'),
  T('munna-bhai-mbbs', M, '🩺', 'Munna Bhai M.B.B.S.', 2003, HI, ['comedy', 'drama'], 'A big-hearted goon enrols in medical college.'),
  T('koi-mil-gaya', M, '👽', 'Koi... Mil Gaya', 2003, HI, ['scifi', 'family'], 'A gentle young man befriends an alien named Jadoo.'),
  T('kal-ho-naa-ho', M, '🌇', 'Kal Ho Naa Ho', 2003, HI, ['romance', 'drama', 'family'], 'A cheerful stranger changes a New York family.'),
  T('baghban', M, '🌳', 'Baghban', 2003, HI, ['family', 'drama'], 'An older couple learns who truly cares for them.'),
  T('swades', M, '🛰️', 'Swades', 2004, HI, ['drama'], 'A NASA scientist returns to an Indian village.'),
  T('main-hoon-na', M, '🎓', 'Main Hoon Na', 2004, HI, ['action', 'comedy'], 'An army major goes undercover as a college student.'),
  T('veer-zaara', M, '✉️', 'Veer-Zaara', 2004, HI, ['romance', 'drama'], 'A love story across the India–Pakistan border.'),
  T('dhoom', M, '🏍️', 'Dhoom', 2004, HI, ['action', 'crime'], 'A cop and a mechanic chase a gang of bike thieves.'),
  T('iqbal', M, '🏏', 'Iqbal', 2005, HI, ['sports', 'drama'], 'A deaf boy from a village dreams of bowling for India.'),
  T('rang-de-basanti', M, '🎨', 'Rang De Basanti', 2006, HI, ['drama', 'historical'], 'Friends making a film about freedom fighters find their voice.'),
  T('lage-raho-munna-bhai', M, '🕊️', 'Lage Raho Munna Bhai', 2006, HI, ['comedy', 'drama'], 'Munna Bhai starts seeing Gandhi, and learns Gandhigiri.'),
  T('krrish', M, '🦸', 'Krrish', 2006, HI, ['scifi', 'action'], 'A boy with special powers becomes a masked hero.'),
  T('don-2006', M, '🕶️', 'Don', 2006, HI, ['action', 'crime'], 'A look-alike takes the place of a wanted crime boss.'),
  T('khosla-ka-ghosla', M, '🏗️', 'Khosla Ka Ghosla!', 2006, HI, ['comedy', 'family'], 'A family plots to win back land from a shady builder.'),
  T('golmaal-2006', M, '🤹', 'Golmaal: Fun Unlimited', 2006, HI, ['comedy'], 'Four friends bluff their way into an elderly couple’s house.'),
  T('phir-hera-pheri', M, '📞', 'Phir Hera Pheri', 2006, HI, ['comedy'], 'The trio are back, and so is the chaos.'),
  T('chak-de-india', M, '🏑', 'Chak De! India', 2007, HI, ['sports', 'drama'], 'A disgraced coach builds a women’s hockey team.'),
  T('taare-zameen-par', M, '🎨', 'Taare Zameen Par', 2007, HI, ['family', 'drama'], 'An art teacher sees what others miss in a struggling boy.'),
  T('jab-we-met', M, '🚆', 'Jab We Met', 2007, HI, ['romance', 'comedy'], 'A chatty girl and a gloomy boy share a train journey.'),
  T('om-shanti-om', M, '🎬', 'Om Shanti Om', 2007, HI, ['romance', 'comedy', 'fantasy'], 'A 1970s junior artist returns in a new life.'),
  T('bhool-bhulaiyaa', M, '🏚️', 'Bhool Bhulaiyaa', 2007, HI, ['horror', 'comedy'], 'A psychiatrist visits a haunted haveli.'),
  T('namastey-london', M, '🇬🇧', 'Namastey London', 2007, HI, ['romance', 'comedy'], 'A London-raised girl and a Punjabi boy with plenty of pride.'),
  T('rab-ne', M, '💞', 'Rab Ne Bana Di Jodi', 2008, HI, ['romance', 'comedy'], 'A shy husband reinvents himself to win his wife’s heart.'),
  T('jodhaa-akbar', M, '🐘', 'Jodhaa Akbar', 2008, HI, ['historical', 'romance'], 'A Mughal emperor and a Rajput princess.'),
  T('jaane-tu', M, '📷', 'Jaane Tu... Ya Jaane Na', 2008, HI, ['romance', 'comedy'], 'Best friends who everyone thinks should be together.'),
  T('a-wednesday', M, '📅', 'A Wednesday!', 2008, HI, ['thriller', 'crime'], 'An ordinary man calls the police with an extraordinary threat.'),
  T('three-idiots', M, '🎓', '3 Idiots', 2009, HI, ['comedy', 'drama'], 'Three engineering students question how we learn.'),
  T('wake-up-sid', M, '📸', 'Wake Up Sid', 2009, HI, ['drama', 'romance'], 'A lazy rich kid grows up with help from a new friend.'),
  T('love-aaj-kal', M, '💘', 'Love Aaj Kal', 2009, HI, ['romance'], 'Modern love set against a love story from the past.'),

  // ---------------------------------------------------------------- Hindi films: 2010s
  T('udaan', M, '🪁', 'Udaan', 2010, HI, ['drama', 'family'], 'A teen who wants to write stands up to his strict father.'),
  T('band-baaja-baaraat', M, '🎺', 'Band Baaja Baaraat', 2010, HI, ['romance', 'comedy'], 'Two young Delhi wedding planners mix business and love.'),
  T('rockstar', M, '🎸', 'Rockstar', 2011, HI, ['music', 'romance', 'drama'], 'A college boy chases heartbreak to become a musician.'),
  T('znmd', M, '🏝️', 'Zindagi Na Milegi Dobara', 2011, HI, ['comedy', 'drama'], 'Three friends, one road trip across Spain.'),
  T('barfi', M, '🍬', 'Barfi!', 2012, HI, ['romance', 'comedy'], 'A charming deaf and mute man and two love stories.'),
  T('english-vinglish', M, '🗽', 'English Vinglish', 2012, HI, ['family', 'drama'], 'A homemaker learns English on a trip to New York.'),
  T('kahaani', M, '🧳', 'Kahaani', 2012, HI, ['thriller', 'mystery'], 'A pregnant woman searches Kolkata for her missing husband.'),
  T('ek-tha-tiger', M, '🐯', 'Ek Tha Tiger', 2012, HI, ['spy', 'action', 'romance'], 'An Indian agent falls for someone he should not.'),
  T('omg', M, '🙏', 'OMG: Oh My God!', 2012, HI, ['comedy', 'drama'], 'A shopkeeper takes God to court over an insurance claim.'),
  T('special-26', M, '🕴️', 'Special 26', 2013, HI, ['crime', 'thriller'], 'Con men pose as tax officers to raid the rich.'),
  T('chennai-express', M, '🚃', 'Chennai Express', 2013, HI, ['comedy', 'action', 'romance'], 'A trip to Rameswaram takes a very wrong turn.'),
  T('yjhd', M, '🏔️', 'Yeh Jawaani Hai Deewani', 2013, HI, ['romance', 'comedy'], 'A trek, a wedding and old friends reconnecting.'),
  T('the-lunchbox', M, '🍱', 'The Lunchbox', 2013, HI, ['romance', 'drama'], 'A mixed-up tiffin leads to letters between strangers.'),
  T('bhaag-milkha-bhaag', M, '🏃', 'Bhaag Milkha Bhaag', 2013, HI, ['sports', 'historical', 'drama'], 'The life and races of the Flying Sikh, Milkha Singh.'),
  T('aashiqui-2', M, '🎤', 'Aashiqui 2', 2013, HI, ['music', 'romance', 'drama'], 'A fading singer helps a young singer find the spotlight.'),
  T('kai-po-che', M, '🏏', 'Kai Po Che!', 2013, HI, ['drama', 'sports'], 'Three Ahmedabad friends start a cricket academy.'),
  T('queen', M, '👑', 'Queen', 2014, HI, ['comedy', 'drama'], 'Jilted before her wedding, she goes on the honeymoon alone.'),
  T('pk', M, '📻', 'PK', 2014, HI, ['comedy', 'scifi'], 'A curious visitor asks innocent questions about everything.'),
  T('two-states', M, '💑', '2 States', 2014, HI, ['romance', 'comedy', 'family'], 'A Punjabi boy and a Tamil girl try to win over both families.'),
  T('mary-kom', M, '🥊', 'Mary Kom', 2014, HI, ['sports', 'drama'], 'The Manipuri boxer who became a world champion.'),
  T('bajrangi-bhaijaan', M, '🙏', 'Bajrangi Bhaijaan', 2015, HI, ['drama', 'family'], 'A kind man helps a lost girl get home across a border.'),
  T('piku', M, '🚕', 'Piku', 2015, HI, ['comedy', 'family'], 'A daughter, her fussy father and a road trip to Kolkata.'),
  T('baby', M, '🕵️', 'Baby', 2015, HI, ['spy', 'thriller', 'action'], 'A secret counter-terror unit races against time.'),
  T('dil-dhadakne-do', M, '🛳️', 'Dil Dhadakne Do', 2015, HI, ['family', 'comedy', 'drama'], 'A rich family’s cruise holiday reveals its cracks.'),
  T('tamasha', M, '🎭', 'Tamasha', 2015, HI, ['romance', 'drama'], 'A storyteller at heart stuck in a very ordinary job.'),
  T('bajirao-mastani', M, '⚔️', 'Bajirao Mastani', 2015, HI, ['historical', 'romance'], 'The Maratha general Bajirao and the warrior princess Mastani.'),
  T('drishyam-hindi', M, '🎞️', 'Drishyam', 2015, HI, ['thriller', 'crime', 'family'], 'A film-loving father protects his family with a perfect plan.'),
  T('dilwale-2015', M, '🎢', 'Dilwale', 2015, HI, ['romance', 'action', 'comedy'], 'Two siblings, two rival families and an old love.'),
  T('dangal', M, '🤼', 'Dangal', 2016, HI, ['sports', 'family', 'drama'], 'A father trains his daughters to be world-class wrestlers.'),
  T('dear-zindagi', M, '🌊', 'Dear Zindagi', 2016, HI, ['drama'], 'A young filmmaker finds calm with an unusual therapist.'),
  T('kapoor-and-sons', M, '📷', 'Kapoor & Sons', 2016, HI, ['family', 'drama', 'comedy'], 'Two brothers come home to a grandfather who wants a photo.'),
  T('ms-dhoni', M, '🏏', 'M.S. Dhoni: The Untold Story', 2016, HI, ['sports', 'drama'], 'A ticket collector from Ranchi becomes India’s captain.'),
  T('sultan', M, '🤼', 'Sultan', 2016, HI, ['sports', 'drama', 'romance'], 'An ageing wrestler steps back into the ring.'),
  T('neerja', M, '✈️', 'Neerja', 2016, HI, ['historical', 'thriller'], 'A young flight attendant’s courage during a hijacking.'),
  T('tiger-zinda-hai', M, '🐅', 'Tiger Zinda Hai', 2017, HI, ['spy', 'action'], 'Agent Tiger returns for a rescue mission.'),
  T('hindi-medium', M, '🏫', 'Hindi Medium', 2017, HI, ['comedy', 'family'], 'Parents go to great lengths for a top school admission.'),
  T('bareilly-ki-barfi', M, '🍬', 'Bareilly Ki Barfi', 2017, HI, ['romance', 'comedy'], 'A small-town girl searches for the author of a book.'),
  T('qarib-qarib-singlle', M, '🧳', 'Qarib Qarib Singlle', 2017, HI, ['romance', 'comedy'], 'Two mismatched people take a trip across India.'),
  T('andhadhun', M, '🎹', 'Andhadhun', 2018, HI, ['thriller', 'crime', 'comedy'], 'A pianist who says he is blind witnesses something he shouldn’t.'),
  T('badhaai-ho', M, '👶', 'Badhaai Ho', 2018, HI, ['comedy', 'family'], 'Grown sons learn their middle-aged parents are expecting.'),
  T('stree', M, '👻', 'Stree', 2018, HI, ['horror', 'comedy'], 'A small town and a ghost who visits during a festival.'),
  T('tumbbad', M, '🪙', 'Tumbbad', 2018, HI, ['horror', 'fantasy', 'historical'], 'A family’s greed and a hidden treasure in a rain-soaked village.'),
  T('raazi', M, '📻', 'Raazi', 2018, HI, ['spy', 'thriller', 'historical'], 'A young woman marries into a Pakistani family as a spy.'),
  T('padmaavat', M, '🏰', 'Padmaavat', 2018, HI, ['historical', 'drama'], 'The legend of Queen Padmavati of Chittor.'),
  T('pad-man', M, '🩹', 'Pad Man', 2018, HI, ['drama', 'comedy'], 'A man sets out to make affordable sanitary pads.'),
  T('gully-boy', M, '🎤', 'Gully Boy', 2019, HI, ['music', 'drama'], 'A young man from Dharavi finds his voice in rap.'),
  T('uri', M, '🪖', 'Uri: The Surgical Strike', 2019, HI, ['action', 'historical'], 'An army officer leads a high-stakes operation.'),
  T('super-30', M, '➗', 'Super 30', 2019, HI, ['drama'], 'A maths teacher coaches poor students for IIT.'),
  T('chhichhore', M, '🏅', 'Chhichhore', 2019, HI, ['comedy', 'drama', 'sports'], 'Old hostel friends remember their college sports days.'),
  T('war', M, '🛩️', 'War', 2019, HI, ['spy', 'action'], 'An agent is sent after his own rogue mentor.'),
  T('kesari', M, '🟧', 'Kesari', 2019, HI, ['historical', 'action'], 'The Battle of Saragarhi: 21 Sikh soldiers hold the fort.'),
  T('mission-mangal', M, '🔴', 'Mission Mangal', 2019, HI, ['drama', 'scifi', 'historical'], 'The scientists behind India’s budget mission to Mars.'),
  T('badla', M, '♟️', 'Badla', 2019, HI, ['thriller', 'mystery'], 'A lawyer questions a businesswoman accused of a crime.'),
  T('dream-girl', M, '📞', 'Dream Girl', 2019, HI, ['comedy'], 'A man who voices women on stage takes a call-centre job.'),

  // ---------------------------------------------------------------- Hindi films: 2020s
  T('tanhaji', M, '⚔️', 'Tanhaji: The Unsung Warrior', 2020, HI, ['historical', 'action'], 'A Maratha warrior’s mission to recapture Kondhana fort.'),
  T('angrezi-medium', M, '🇬🇧', 'Angrezi Medium', 2020, HI, ['comedy', 'family'], 'A sweet-shop owner goes all out to send his daughter to London.'),
  T('cargo', M, '🚀', 'Cargo', 2020, HI, ['scifi', 'drama'], 'A spaceship crew prepares souls for their next life.'),
  T('raat-akeli-hai', M, '🌙', 'Raat Akeli Hai', 2020, HI, ['crime', 'mystery'], 'A cop investigates a death on a wedding night.'),
  T('shershaah', M, '🏔️', 'Shershaah', 2021, HI, ['historical', 'action', 'romance'], 'The life of Kargil war hero Captain Vikram Batra.'),
  T('sardar-udham', M, '🧣', 'Sardar Udham', 2021, HI, ['historical', 'drama'], 'A revolutionary’s long road after Jallianwala Bagh.'),
  T('eighty-three', M, '🏆', '83', 2021, HI, ['sports', 'historical'], 'India’s underdog win at the 1983 Cricket World Cup.'),
  T('pagglait', M, '🌼', 'Pagglait', 2021, HI, ['family', 'comedy', 'drama'], 'A young widow finds herself during a houseful of mourning.'),
  T('brahmastra', M, '🔥', 'Brahmastra Part One: Shiva', 2022, HI, ['fantasy', 'action'], 'A DJ discovers a connection to fire and ancient weapons.'),
  T('bhediya', M, '🐺', 'Bhediya', 2022, HI, ['horror', 'comedy'], 'A road contractor in Arunachal gets bitten by something wild.'),
  T('bhool-bhulaiyaa-2', M, '🏚️', 'Bhool Bhulaiyaa 2', 2022, HI, ['horror', 'comedy'], 'A fake psychic walks into a very real haunting.'),
  T('pathaan', M, '🕶️', 'Pathaan', 2023, HI, ['spy', 'action'], 'An exiled agent returns to stop a deadly attack.'),
  T('jawan', M, '🚆', 'Jawan', 2023, HI, ['action', 'thriller'], 'A man with a mission hijacks a Mumbai metro.'),
  T('twelfth-fail', M, '📚', '12th Fail', 2023, HI, ['drama'], 'A boy from Chambal refuses to give up on the UPSC dream.'),
  T('rocky-aur-rani', M, '💃', 'Rocky Aur Rani Kii Prem Kahaani', 2023, HI, ['romance', 'comedy', 'family'], 'A Punjabi hunk and a Bengali journalist swap families.'),
  T('dunki', M, '✈️', 'Dunki', 2023, HI, ['comedy', 'drama'], 'Friends from Punjab dream of making it to London.'),
  T('sam-bahadur', M, '🎖️', 'Sam Bahadur', 2023, HI, ['historical', 'drama'], 'The life of Field Marshal Sam Manekshaw.'),
  T('jaane-jaan', M, '🧮', 'Jaane Jaan', 2023, HI, ['thriller', 'mystery'], 'A maths teacher quietly helps his neighbour out of trouble.'),
  T('laapataa-ladies', M, '👰', 'Laapataa Ladies', 2024, HI, ['comedy', 'drama'], 'Two brides get swapped on a crowded train.'),
  T('stree-2', M, '👻', 'Stree 2', 2024, HI, ['horror', 'comedy'], 'Chanderi faces a brand-new supernatural problem.'),
  T('bhool-bhulaiyaa-3', M, '🏚️', 'Bhool Bhulaiyaa 3', 2024, HI, ['horror', 'comedy'], 'Rooh Baba takes on another palace with a past.'),
  T('munjya', M, '🌳', 'Munjya', 2024, HI, ['horror', 'comedy'], 'A shy young man and a mischievous spirit from a tree.'),
  T('shaitaan', M, '📱', 'Shaitaan', 2024, HI, ['horror', 'thriller'], 'A stranger takes control of a family’s daughter.'),
  T('fighter', M, '✈️', 'Fighter', 2024, HI, ['action'], 'Air Force pilots on a high-stakes mission.'),
  T('crew', M, '🧳', 'Crew', 2024, HI, ['comedy', 'crime'], 'Three flight attendants stumble onto a gold-smuggling plan.'),
  T('srikanth', M, '👓', 'Srikanth', 2024, HI, ['drama'], 'A visually impaired boy grows up to build his own company.'),
  T('merry-christmas', M, '🎄', 'Merry Christmas', 2024, HI, ['thriller', 'mystery', 'romance'], 'Two strangers meet on one strange Christmas Eve.'),
  T('hanuman-2005', M, '🐒', 'Hanuman', 2005, HI, ['animation', 'family', 'fantasy'], 'The childhood adventures of Hanuman, animated.'),

  // ---------------------------------------------------------------- Tamil
  T('roja', M, '🌹', 'Roja', 1992, TA, ['romance', 'thriller'], 'A village bride searches for her husband who has been taken.'),
  T('bombay', M, '🌧️', 'Bombay', 1995, TA, ['romance', 'drama'], 'A Hindu man and a Muslim woman marry and build a life.'),
  T('anbe-sivam', M, '🚌', 'Anbe Sivam', 2003, TA, ['drama', 'comedy'], 'Two opposite men travel together after a flood.'),
  T('enthiran', M, '🤖', 'Enthiran', 2010, TA, ['scifi', 'action'], 'A scientist builds a humanoid robot that learns to feel.'),
  T('vtv', M, '💌', 'Vinnaithaandi Varuvaayaa', 2010, TA, ['romance', 'music'], 'An aspiring filmmaker falls for the girl upstairs.'),
  T('vikram-vedha', M, '♠️', 'Vikram Vedha', 2017, TA, ['crime', 'thriller'], 'A cop and a gangster trade stories and questions.'),
  T('ninety-six', M, '📷', '96', 2018, TA, ['romance', 'drama'], 'School sweethearts meet again at a reunion.'),
  T('kaithi', M, '🚚', 'Kaithi', 2019, TA, ['action', 'thriller'], 'A just-released prisoner drives through one dangerous night.'),
  T('soorarai-pottru', M, '✈️', 'Soorarai Pottru', 2020, TA, ['drama'], 'A village boy dreams of a low-cost airline for all.'),
  T('vikram-2022', M, '🎯', 'Vikram', 2022, TA, ['action', 'thriller'], 'A special agent investigates a string of masked attacks.'),
  T('ponniyin-selvan', M, '👑', 'Ponniyin Selvan: I', 2022, TA, ['historical', 'action'], 'Palace intrigue in the Chola kingdom.'),
  T('jailer', M, '🔑', 'Jailer', 2023, TA, ['action', 'comedy'], 'A retired jailer steps back in to protect his family.'),
  T('kaaka-muttai', M, '🍕', 'Kaaka Muttai', 2015, TA, ['family', 'comedy'], 'Two slum kids save up to taste pizza for the first time.'),
  T('elephant-whisperers', M, '🐘', 'The Elephant Whisperers', 2022, TA, ['documentary', 'family'], 'A couple in Tamil Nadu raises an orphaned baby elephant.'),

  // ---------------------------------------------------------------- Telugu
  T('magadheera', M, '🐎', 'Magadheera', 2009, TE, ['fantasy', 'romance', 'action'], 'A love story that spans two lifetimes, 400 years apart.'),
  T('eega', M, '🪰', 'Eega', 2012, TE, ['fantasy', 'action', 'comedy'], 'A man reborn as a housefly sets out to protect his love.'),
  T('baahubali', M, '🏰', 'Baahubali: The Beginning', 2015, TE, ['fantasy', 'action', 'historical'], 'A young man climbs a waterfall into a kingdom’s past.'),
  T('baahubali-2', M, '⚔️', 'Baahubali 2: The Conclusion', 2017, TE, ['fantasy', 'action', 'historical'], 'The epic story of Mahishmati reaches its end.'),
  T('pelli-choopulu', M, '☕', 'Pelli Choopulu', 2016, TE, ['romance', 'comedy'], 'A marriage meeting turns into a food-truck partnership.'),
  T('mahanati', M, '🎞️', 'Mahanati', 2018, TE, ['historical', 'drama'], 'The life of legendary actress Savitri.'),
  T('jersey', M, '🏏', 'Jersey', 2019, TE, ['sports', 'drama', 'family'], 'A former cricketer returns to the game at 36 for his son.'),
  T('ala-vaikunthapurramuloo', M, '🏠', 'Ala Vaikunthapurramuloo', 2020, TE, ['family', 'comedy', 'action'], 'A young man discovers he was swapped at birth.'),
  T('pushpa', M, '🪵', 'Pushpa: The Rise', 2021, TE, ['action', 'crime'], 'A labourer rises in the red sandalwood smuggling trade.'),
  T('rrr', M, '🔥', 'RRR', 2022, TE, ['action', 'historical'], 'Two revolutionaries, one huge friendship, 1920s India.'),
  T('sita-ramam', M, '✉️', 'Sita Ramam', 2022, TE, ['romance', 'historical'], 'A soldier’s love story told through old letters.'),
  T('karthikeya-2', M, '🦚', 'Karthikeya 2', 2022, TE, ['mystery', 'fantasy', 'action'], 'A doctor chases an ancient secret linked to Krishna.'),
  T('hanu-man', M, '💪', 'Hanu-Man', 2024, TE, ['fantasy', 'action'], 'A village thief gains powers from a mysterious gem.'),
  T('kalki-2898-ad', M, '🚀', 'Kalki 2898 AD', 2024, TE, ['scifi', 'action', 'fantasy'], 'A far-future city and a myth that returns.'),

  // ---------------------------------------------------------------- Malayalam
  T('kilukkam', M, '📸', 'Kilukkam', 1991, ML, ['comedy', 'romance'], 'A tour guide, a photographer and a runaway girl in Ooty.'),
  T('manichitrathazhu', M, '🔒', 'Manichitrathazhu', 1993, ML, ['horror', 'mystery', 'drama'], 'A family moves into an old tharavad with a locked room.'),
  T('drishyam-malayalam', M, '🎞️', 'Drishyam', 2013, ML, ['thriller', 'crime', 'family'], 'A cable-TV owner’s love of films helps him protect his family.'),
  T('bangalore-days', M, '🏙️', 'Bangalore Days', 2014, ML, ['family', 'comedy', 'romance'], 'Three cousins start new lives in Bengaluru.'),
  T('premam', M, '🦋', 'Premam', 2015, ML, ['romance', 'comedy'], 'One man, three stages of love.'),
  T('charlie-2015', M, '🎨', 'Charlie', 2015, ML, ['romance', 'drama'], 'A woman follows the trail of a free-spirited stranger.'),
  T('maheshinte-prathikaaram', M, '📷', 'Maheshinte Prathikaaram', 2016, ML, ['comedy', 'drama'], 'A village photographer makes a vow after a public brawl.'),
  T('kumbalangi-nights', M, '🌙', 'Kumbalangi Nights', 2019, ML, ['family', 'drama', 'comedy'], 'Four brothers in a fishing village learn to be a family.'),
  T('home-2021', M, '📱', '#Home', 2021, ML, ['family', 'comedy', 'drama'], 'A dad tries to keep up with his phone-glued sons.'),
  T('minnal-murali', M, '⚡', 'Minnal Murali', 2021, ML, ['fantasy', 'action', 'comedy'], 'A village tailor gets powers after a lightning strike.'),
  T('twenty-eighteen', M, '🌧️', '2018', 2023, ML, ['drama', 'historical'], 'Ordinary people become heroes in the 2018 Kerala floods.'),
  T('manjummel-boys', M, '🕳️', 'Manjummel Boys', 2024, ML, ['thriller', 'drama'], 'Friends on a trip to Kodaikanal face a deep cave.'),
  T('bramayugam', M, '🕯️', 'Bramayugam', 2024, ML, ['horror', 'historical'], 'A singer takes shelter in a mysterious old mansion.'),
  T('premalu', M, '💕', 'Premalu', 2024, ML, ['romance', 'comedy'], 'A fresh graduate in Hyderabad falls for a colleague.'),

  // ---------------------------------------------------------------- Kannada
  T('lucia', M, '💤', 'Lucia', 2013, KN, ['scifi', 'thriller'], 'A cinema usher takes a pill that turns dreams into a second life.'),
  T('u-turn', M, '↩️', 'U Turn', 2016, KN, ['thriller', 'horror', 'mystery'], 'A journalist investigates a flyover where rules are broken.'),
  T('kirik-party', M, '🎓', 'Kirik Party', 2016, KN, ['comedy', 'romance'], 'Engineering college pranks, friendships and first love.'),
  T('kgf-chapter-1', M, '⛏️', 'K.G.F: Chapter 1', 2018, KN, ['action', 'crime'], 'A man rises in the gold mines of Kolar.'),
  T('kantara', M, '🔥', 'Kantara', 2022, KN, ['thriller', 'fantasy', 'drama'], 'Forest land, folk deities and a village’s rebel.'),
  T('sapta-sagaradaache-ello', M, '🌊', 'Sapta Sagaradaache Ello', 2023, KN, ['romance', 'drama'], 'A young couple dreams of a home by the sea.'),

  // ---------------------------------------------------------------- Bengali
  T('pather-panchali', M, '🚂', 'Pather Panchali', 1955, BN, ['drama', 'family'], 'A boy named Apu grows up in a Bengal village.'),
  T('mahanagar', M, '🏙️', 'Mahanagar', 1963, BN, ['drama', 'family'], 'A Calcutta housewife takes a job and changes her family.'),
  T('charulata', M, '📖', 'Charulata', 1964, BN, ['drama', 'romance'], 'A lonely wife finds her voice as a writer.'),
  T('goopy-gyne', M, '🥁', 'Goopy Gyne Bagha Byne', 1969, BN, ['fantasy', 'music', 'comedy'], 'Two hopeless musicians get three magical boons.'),
  T('sonar-kella', M, '🏜️', 'Sonar Kella', 1974, BN, ['mystery', 'family'], 'Detective Feluda follows a boy’s memories to Rajasthan.'),
  T('bela-seshe', M, '🌇', 'Bela Seshe', 2015, BN, ['family', 'drama'], 'An older man shocks his family by asking for a separation.'),

  // ---------------------------------------------------------------- Marathi
  T('zapatlela', M, '🪆', 'Zapatlela', 1993, MR, ['horror', 'comedy'], 'A ventriloquist’s doll holds a very unwelcome spirit.'),
  T('shwaas', M, '👴', 'Shwaas', 2004, MR, ['family', 'drama'], 'A grandfather and his grandson face a hard medical choice.'),
  T('harishchandrachi-factory', M, '🎥', 'Harishchandrachi Factory', 2009, MR, ['historical', 'comedy'], 'Dadasaheb Phalke makes India’s first feature film.'),
  T('court', M, '⚖️', 'Court', 2014, MR, ['drama'], 'A folk singer’s trial, seen through ordinary lives.'),
  T('killa', M, '🏯', 'Killa', 2014, MR, ['family', 'drama'], 'A boy adjusts to a new coastal town after a loss.'),
  T('sairat', M, '💞', 'Sairat', 2016, MR, ['romance', 'drama', 'music'], 'Two teens from different worlds fall in love.'),
  T('natsamrat', M, '🎭', 'Natsamrat', 2016, MR, ['drama', 'family'], 'A retired stage legend struggles with life after the stage.'),
  T('baipan-bhari-deva', M, '💃', 'Baipan Bhari Deva', 2023, MR, ['comedy', 'family'], 'Six estranged sisters reunite for a dance competition.'),

  // ---------------------------------------------------------------- Gujarati
  T('kevi-rite-jaish', M, '✈️', 'Kevi Rite Jaish', 2012, GU, ['comedy', 'drama'], 'A young man’s family is obsessed with getting to America.'),
  T('bey-yaar', M, '🎨', 'Bey Yaar', 2014, GU, ['comedy', 'drama'], 'Two Ahmedabad friends get caught up in an art scam.'),
  T('chhello-divas', M, '🎒', 'Chhello Divas', 2015, GU, ['comedy'], 'A gang of college friends and their last days together.'),
  T('gujjubhai-the-great', M, '😄', 'Gujjubhai the Great', 2015, GU, ['comedy', 'family'], 'A dad’s plans to stop his daughter’s romance backfire.'),
  T('wrong-side-raju', M, '🚗', 'Wrong Side Raju', 2016, GU, ['crime', 'drama'], 'A driver in Ahmedabad is caught up in a hit-and-run case.'),
  T('hellaro', M, '💃', 'Hellaro', 2019, GU, ['drama', 'music', 'historical'], 'Women in a Kutch village find freedom in garba.'),
  T('chaal-jeevi-laiye', M, '🏔️', 'Chaal Jeevi Laiye!', 2019, GU, ['family', 'comedy'], 'A workaholic son and his fun dad take a trip to the Himalayas.'),
  T('chhello-show', M, '🎞️', 'Chhello Show', 2021, GU, ['drama', 'family'], 'A boy in Saurashtra falls in love with cinema.'),
  T('three-ekka', M, '🃏', '3 Ekka', 2023, GU, ['comedy'], 'Three friends try a get-rich-quick plan.'),

  // ---------------------------------------------------------------- Punjabi
  T('jatt-and-juliet', M, '🇨🇦', 'Jatt & Juliet', 2012, PA, ['romance', 'comedy'], 'A village boy and a city girl travel to Canada.'),
  T('carry-on-jatta', M, '🤥', 'Carry On Jatta', 2012, PA, ['comedy'], 'One small lie grows into a giant family mix-up.'),
  T('angrej', M, '🌾', 'Angrej', 2015, PA, ['romance', 'historical', 'comedy'], 'Village love and match-making in 1940s Punjab.'),
  T('sardaarji', M, '👻', 'Sardaarji', 2015, PA, ['horror', 'comedy', 'fantasy'], 'A ghost-catcher meets a ghost he would rather befriend.'),
  T('ardaas', M, '🙏', 'Ardaas', 2016, PA, ['drama', 'family'], 'A teacher brings hope to a troubled village.'),
  T('qismat', M, '💔', 'Qismat', 2018, PA, ['romance', 'drama'], 'A college love story shaped by fate.'),
  T('chal-mera-putt', M, '🇬🇧', 'Chal Mera Putt', 2019, PA, ['comedy', 'drama'], 'Punjabi and Pakistani migrants help each other in the UK.'),
  T('sufna', M, '🌾', 'Sufna', 2020, PA, ['romance'], 'A farmhand and a girl who picks cotton fall in love.'),
  T('honsla-rakh', M, '👶', 'Honsla Rakh', 2021, PA, ['comedy', 'family'], 'A single dad in Vancouver tries to find love again.'),
  T('tabbar', S, '🏠', 'Tabbar', 2021, PA, ['crime', 'thriller', 'family'], 'A father will do anything to protect his family’s secret.'),
  T('mastaney', M, '⚔️', 'Mastaney', 2023, PA, ['historical', 'action'], 'Sikh warriors stand up to Nadir Shah’s army.'),

  // ---------------------------------------------------------------- Korean
  T('squid-game', S, '🦑', 'Squid Game', 2021, KO, ['thriller', 'drama'], 'People in debt play childhood games for huge prize money.'),
  T('cloy', S, '🪂', 'Crash Landing on You', 2019, KO, ['romance', 'comedy'], 'A paraglider lands in North Korea and finds love.'),
  T('goblin', S, '🕯️', 'Guardian: The Lonely and Great God', 2016, KO, ['fantasy', 'romance'], 'An immortal goblin waits for the bride who can end his curse.'),
  T('reply-1988', S, '📼', 'Reply 1988', 2015, KO, ['family', 'comedy', 'drama'], 'Five families and their kids on one Seoul alley in 1988.'),
  T('extraordinary-attorney-woo', S, '🐋', 'Extraordinary Attorney Woo', 2022, KO, ['drama', 'comedy'], 'A brilliant autistic lawyer starts at a big law firm.'),
  T('business-proposal', S, '💼', 'Business Proposal', 2022, KO, ['romance', 'comedy'], 'A blind date stand-in meets her own CEO.'),
  T('itaewon-class', S, '🍜', 'Itaewon Class', 2020, KO, ['drama'], 'A young man opens a small restaurant to take on a giant.'),
  T('hospital-playlist', S, '🎸', 'Hospital Playlist', 2020, KO, ['drama', 'comedy', 'music'], 'Five doctor friends who also play in a band.'),
  T('vincenzo', S, '🧥', 'Vincenzo', 2021, KO, ['crime', 'comedy'], 'An Italian-Korean lawyer takes on a greedy company.'),
  T('hometown-cha-cha-cha', S, '🌊', 'Hometown Cha-Cha-Cha', 2021, KO, ['romance', 'comedy'], 'A city dentist moves to a seaside village.'),
  T('descendants-of-the-sun', S, '☀️', 'Descendants of the Sun', 2016, KO, ['romance', 'action'], 'A soldier and a surgeon meet in a disaster zone.'),
  T('queen-of-tears', S, '👑', 'Queen of Tears', 2024, KO, ['romance', 'drama', 'comedy'], 'A married couple rediscover each other.'),
  T('moving', S, '🎈', 'Moving', 2023, KO, ['fantasy', 'action', 'family'], 'Teens with hidden powers and parents with secrets.'),
  T('all-of-us-are-dead', S, '🏫', 'All of Us Are Dead', 2022, KO, ['horror', 'action'], 'Students trapped in a high school during an outbreak.'),
  T('kingdom', S, '👑', 'Kingdom', 2019, KO, ['horror', 'historical', 'thriller'], 'A crown prince faces a mysterious plague in Joseon Korea.'),
  T('sweet-home', S, '🏢', 'Sweet Home', 2020, KO, ['horror', 'fantasy'], 'Apartment residents survive as people turn into monsters.'),
  T('parasite', M, '🪨', 'Parasite', 2019, KO, ['thriller', 'drama', 'comedy'], 'A poor family works its way into a rich household.'),
  T('train-to-busan', M, '🚄', 'Train to Busan', 2016, KO, ['horror', 'action'], 'A dad and daughter on a train during an outbreak.'),

  // ---------------------------------------------------------------- Japanese: anime and Ghibli
  T('my-neighbor-totoro', M, '🌳', 'My Neighbor Totoro', 1988, JA, ['animation', 'anime', 'family'], 'Two sisters meet gentle forest spirits in the countryside.'),
  T('princess-mononoke', M, '🐺', 'Princess Mononoke', 1997, JA, ['animation', 'anime', 'fantasy'], 'A prince is caught between forest gods and an iron town.'),
  T('spirited-away', M, '🛁', 'Spirited Away', 2001, JA, ['animation', 'anime', 'fantasy'], 'A girl works in a bathhouse for spirits to save her parents.'),
  T('howls-moving-castle', M, '🏰', "Howl's Moving Castle", 2004, JA, ['animation', 'anime', 'fantasy'], 'A young hatter is cursed and finds a walking castle.'),
  T('your-name', M, '☄️', 'Your Name', 2016, JA, ['animation', 'anime', 'romance'], 'Two teens mysteriously swap bodies across Japan.'),
  T('suzume', M, '🚪', 'Suzume', 2022, JA, ['animation', 'anime', 'fantasy'], 'A girl travels Japan closing doors that unleash disasters.'),
  T('boy-and-the-heron', M, '🪶', 'The Boy and the Heron', 2023, JA, ['animation', 'anime', 'fantasy'], 'A grieving boy follows a heron into another world.'),
  T('attack-on-titan', S, '🧱', 'Attack on Titan', 2013, JA, ['anime', 'action', 'fantasy'], 'Humanity hides behind walls from giant beings.'),
  T('demon-slayer', S, '🗡️', 'Demon Slayer', 2019, JA, ['anime', 'action', 'fantasy'], 'A kind boy becomes a demon hunter to save his sister.'),
  T('one-piece-anime', S, '🏴‍☠️', 'One Piece', 1999, JA, ['anime', 'action', 'comedy'], 'A stretchy pirate sets out to find the greatest treasure.'),
  T('naruto', S, '🍥', 'Naruto', 2002, JA, ['anime', 'action'], 'An outcast ninja dreams of becoming his village’s leader.'),
  T('death-note', S, '📓', 'Death Note', 2006, JA, ['anime', 'thriller', 'mystery'], 'A student finds a notebook with deadly power.'),
  T('spy-x-family', S, '🥜', 'Spy x Family', 2022, JA, ['anime', 'spy', 'comedy'], 'A spy, an assassin and a mind reader pretend to be a family.'),
  T('jujutsu-kaisen', S, '👁️', 'Jujutsu Kaisen', 2020, JA, ['anime', 'action', 'fantasy'], 'A student joins a school that fights curses.'),
  T('frieren', S, '🌸', "Frieren: Beyond Journey's End", 2023, JA, ['anime', 'fantasy', 'drama'], 'An elf mage learns what her human friends meant to her.'),
  T('haikyu', S, '🏐', 'Haikyu!!', 2014, JA, ['anime', 'sports', 'comedy'], 'A short boy with a huge jump joins a volleyball team.'),
  T('fmab', S, '⚗️', 'Fullmetal Alchemist: Brotherhood', 2009, JA, ['anime', 'fantasy', 'action'], 'Two brothers use alchemy to fix a big mistake.'),

  // ---------------------------------------------------------------- Spanish
  T('money-heist', S, '🎭', 'Money Heist', 2017, ES, ['crime', 'thriller'], 'A mastermind and his crew take over the Royal Mint of Spain.'),
  T('betty-la-fea', S, '👓', 'Yo soy Betty, la fea', 1999, ES, ['comedy', 'romance'], 'A brilliant, unfashionable assistant at a fashion house.'),
  T('pans-labyrinth', M, '🗝️', "Pan's Labyrinth", 2006, ES, ['fantasy', 'drama', 'historical'], 'A girl in 1940s Spain finds a mysterious faun’s maze.'),
  T('the-orphanage', M, '🏚️', 'The Orphanage', 2007, ES, ['horror', 'mystery'], 'A woman reopens the orphanage where she grew up.'),
  T('instructions-not-included', M, '👧', 'Instructions Not Included', 2013, ES, ['comedy', 'family'], 'A carefree man is suddenly left to raise a baby.'),
  T('the-invisible-guest', M, '🔐', 'The Invisible Guest', 2016, ES, ['thriller', 'mystery'], 'A businessman and his lawyer piece together one night.'),
  T('roma', M, '🎞️', 'Roma', 2018, ES, ['drama', 'family'], 'A year in the life of a housekeeper in 1970s Mexico City.'),

  // ---------------------------------------------------------------- Other languages
  T('dark', S, '🕳️', 'Dark', 2017, OT, ['scifi', 'mystery', 'thriller'], 'A missing child in a German town unlocks a time puzzle.'),
  T('lupin', S, '🎩', 'Lupin', 2021, OT, ['crime', 'thriller'], 'A gentleman thief in Paris follows his literary hero.'),
  T('amelie', M, '🍓', 'Amélie', 2001, OT, ['romance', 'comedy'], 'A shy Parisian waitress secretly improves other lives.'),
  T('intouchables', M, '♿', 'The Intouchables', 2011, OT, ['comedy', 'drama'], 'A rich man and his unlikely carer become best friends.'),
  T('life-is-beautiful', M, '🎪', 'Life Is Beautiful', 1997, OT, ['drama', 'comedy', 'historical'], 'A father uses humour to protect his son in wartime.'),
];
